### ISSUE TITLE
Conversion fails at certain lines

### ISSUE THREAD

**Issue by sonukapoor** [Keyang/node-csvtojson#104]
Hi, 

Thank you for providing this plugin. I am trying to convert a csv file into json that I received from our vendor. The first 19 lines or so work fine, but after that the next line merges into the same json object. 
The output of the JSON looks like this:

```
VendorDescription: 'NIKE',
CurrentRetail: '150.0000"\n"613415817',
field19: 'Shoes',

```

613415817 is actually part of the next row. Do I need to set the EOL to "\n" ?

**Comment by Keyang** [comment]
could you send the row from csv which cause this?

~Keyang

**Comment by sonukapoor** [comment]
@Keyang I would like to send you the file privately if that is ok? Can you share your email?

**Comment by Keyang** [comment]
yes.
keyang.xiang@gmail.com

**Comment by sonukapoor** [comment]
@Keyang file sent.

**Comment by sonukapoor** [comment]
Here is the code I have used:

```
var Converter = require("csvtojson").Converter;
var converter = new Converter({});

converter.fromFile(fileToProcess, function (err, result)
{
    console.log("done", result);
});
```

**Comment by sonukapoor** [comment]
Resolved.

**Comment by jack-wi** [comment]
@sonukapoor Do you remember how you solved this? Having the exact same issue.
