### ISSUE TITLE
Piping converter output to MongoDb bulk insert

### ISSUE THREAD

**Issue by pmosconi** [Keyang/node-csvtojson#109]
Hi,
I am trying to pipe the converter result into a MongoDb bulk insert:
`rs.pipe(converter).pipe(bulkWriter);`

MongoDb insert fails:
`MongoError: error parsing element 0 of field documents :: caused by :: wrong type for '0' field, expected object, found 0: ... `

The reason seems to be that the json row out of the converter is { "key": value } while MongoDb expects { key: value }.

I am totally confused about how and where to do the trasformation (from string to object?).

Thanks for any help
paolo

**Comment by Keyang** [comment]
what lib you used for bulkWriter?

~Keyang

**Comment by pmosconi** [comment]
I am testing bulk-mongo [https://github.com/valango/bulk-mongo](url) , but I am open to any suggestion.
Thanks
paolo

**Comment by Keyang** [comment]
Looks like bulk-mongo only  compatible with objectMode:true
give a try https://github.com/Keyang/node-csvtojson#stream-options
This should fix the issue.

**Comment by pmosconi** [comment]
I had in fact overlooked the stream options for both converter and bulkWriter, but setting both of them to the same objectMode (true or false) doesn't change the result.
Thanks for your help.
paolo

**Comment by Keyang** [comment]
could you show me the code you setup the objectMode in the converter?
also double check if the csvtojson version being upgraded to 1.0.0

~Keyang

**Comment by pmosconi** [comment]
I created a simple test with very few lines (obviously if the csv file would really be this, streaming wouldn't be needed).

    "use strict"; // node ver 4.3.2

    // external dependencies
    require('stream');
    const Converter = require("csvtojson").Converter;   // 1.0.0
    const mongodb = require('mongodb');                 // 2.1.18
    const bulkMongo = require('bulk-mongo');            // 0.1.0

    const rs = require('fs').ReadStream('Test.csv');
    /* THIS IS THE CONTENT OF Test.csv FILE
    prod_cod;prod_desc;bar_barcode;livello1;descrizione1
    3DP300077205;JUST DANCE 2016 PS4;1,00001E+12;1;Livello1
    3DP300077205;JUST DANCE 2016 PS4;3,30722E+12;1;Livello1
    3DP300076857;ASSASSIN'S CREED SYNDICATE SPECIAL ITA PS4;1E+12;1;Livello1
    3DP300076857;ASSASSIN'S CREED SYNDICATE SPECIAL ITA PS4;3,30722E+12;1;Livello1
    3DP300077179;JUST DANCE 2016 PS3;1,00001E+12;1;Livello1
    3DP300077179;JUST DANCE 2016 PS3;3,30722E+12;1;Livello1
    3DP300076924;ASSASSIN'S CREED SYNDICATE SPECIAL ITA XBOX ONE;1E+12;1;Livello1
    3DP300076924;ASSASSIN'S CREED SYNDICATE SPECIAL ITA XBOX ONE;3,30722E+12;1
    3DP300077803;JUST DANCE DISNEY PARTY 2 XBOX ONE;1,00001E+12;1;Livello1
    */

    // project dependencies
    const config = require('./config'); // mongodb connection string

    // CSV Converter params
    const params = {
        constructResult: false, //for big csv data 
        delimiter: ";"
    };

    // init csv converter
    let converter = new Converter(params, {
        objectMode:false, 
        highWaterMark:256
    });
    converter.on('record_parsed', (resultRow,rawRow,rowIndex) => {
    console.log(resultRow.prod_cod) 
    });


    // Connect to DB
    let client = mongodb.MongoClient;

    console.log('Connect to Db ...');

    client.connect(config.getDbConnectionString(), (err, db) => {
        if (err) throw err;

        let factory_function = bulkMongo(db)
        let bulkWriter = factory_function('products', {
            objectMode: false,
            highWaterMark: 256,
            bulkSize: 2
        });
        bulkWriter.on('error', (err) => { 
            throw err; 
        });
        bulkWriter.on('inserts', (result) => { 
            console.log(result); 
        });
        bulkWriter.on('finish', () => { 
            console.log('Finished'); 
            process.exit(0);
        });

        rs.pipe(converter)
            .pipe(bulkWriter);

    });

**Comment by Keyang** [comment]
Hi,
Setup Converter to use objectMode seems working. following code works here:

"use strict"; // node ver 4.3.2

// external dependencies
require('stream');
const Converter = require("csvtojson").Converter;   // 1.0.0
const mongodb = require('mongodb');                 // 2.1.18
const bulkMongo = require('bulk-mongo');            // 0.1.0

const rs = require('fs').ReadStream('Test.csv');

const params = {
    constructResult: false, //for big csv data
    delimiter: ";"
};

// init csv converter
let converter = new Converter(params, {
    objectMode:true,
    highWaterMark:256
});
converter.on('record_parsed', (resultRow,rawRow,rowIndex) => {
console.log(resultRow.prod_cod)
});


// Connect to DB
let client = mongodb.MongoClient;

console.log('Connect to Db ...');

client.connect("mongodb://127.0.0.1/test", (err, db) => {
    if (err) throw err;

    let factory_function = bulkMongo(db)
    let bulkWriter = factory_function('products');
    bulkWriter.on('error', (err) => {
        throw err;
    });
    bulkWriter.on('inserts', (result) => {
        console.log(result);
    });
    bulkWriter.on('finish', () => {
        console.log('Finished');
        process.exit(0);
    });

    rs.pipe(converter)
        .pipe(bulkWriter);

});


Regards,
Keyang

**Comment by pmosconi** [comment]
Yes, it's working!!
I'm testing with 250k+ record as I'm writing this.

Would you care to explain a bit for an old programmer / node.js newb?

Thanks a lot for your help
paolo

**Comment by Keyang** [comment]
Good luck with real data.

if objectMode is false or not set, up stream will push buffer or string to
downstream. If downstream by default set objectMode with true, the passed
string or buffer will not be parsed correctly.
So you will need both up/down stream being setup with objectMode:true

~Keyang

**Comment by mtebele** [comment]
For some reason it has stopped working on v1.0.2.

I tried with the same code as @Keyang in v1.0.2 and it was throwing the error
`MongoError: error parsing element 0 of field documents :: caused by :: wrong type for '0' field, expected object, found 0: ...`

In v1.0.0 works well.

**Comment by Keyang** [comment]
I cannot see the problem.
Would you mind upload the code you have problem with?

~Keyang

**Comment by mtebele** [comment]
My mistake, I was trying on a previous version.
It works well in v1.*
