### ISSUE TITLE
Bug: Pausing the readstream does not pause "record_parsed"

### ISSUE THREAD

**Issue by sonukapoor** [Keyang/node-csvtojson#110]
The below code shows that "record_parsed" continues to run although the stream has been paused.
This causes the rowIndex to advance and skip rows while the stream is paused. 
```
var rs = fs.createReadStream(fileToProcess)
                            .pipe(converter);

converter.on("record_parsed", function (jsonObj,rawRow,rowIndex) {
    if (rs.isPaused())
    {
       console.log("I am still running ", rowIndex); 
    }
    else 
    {
        rs.pause();
    }
});
```

**Comment by Keyang** [comment]
var rs = fs.createReadStream(fileToProcess)
                            .pipe(converter); // rs pointing to converter.


code above returns the converter not the readable stream.

you need do following:

var rs = fs.createReadStream(fileToProcess); //rs pointing to file read stream.

rs.pipe(converter);


///on error

rs.pause();

**Comment by sonukapoor** [comment]
Thank you. That was a bug on my end.
