### ISSUE TITLE
Get the number of rows in the CSV file being processed

### ISSUE THREAD

**Issue by mayurtanna** [Keyang/node-csvtojson#112]
Hi,

This plugin works great with my CSV file so no potential issues. I am requesting an enhancement.  

I have the following case where I need to know total number of rows available in the csv being processed. 

I am converting my csv to json and saving those json objects in my database.

I need to send one email from the system with the number of records inserted, failed and updated in the database once the CSV is parsed. The database operation gives me the status whether the record is inserted or failed and that's how I am calculating the inserted and failed count.

The 'end_parsed' callback is there but it is just getting executed when parsing is done. But in my case, data is still being saved in the database so I am not getting the exact number of saved/failed record count. 

What I was thinking is that if I know the total number of rows available in csv, I can anyhow compare with row_index in 'record_parsed' event and send the email if it is the last record.
Not sure if there is any better way to achieve this.

Thank you.

**Comment by Keyang** [comment]
row index is already populated for each json being emitted
