### ISSUE TITLE
How to deal with Chinese GBK character 

### ISSUE THREAD

**Issue by beiermosi** [Keyang/node-csvtojson#114]
a csv file from server is GBK encode,
how to set csvtojson to handle this kind of staff?

**Comment by Keyang** [comment]
Hi,
You will need to convert the encoding first to utf8 through streaming.
there are plenty of libraries out there doing this.
see: https://github.com/Keyang/node-csvtojson/issues/31
and https://github.com/Keyang/node-csvtojson/issues/84

Regards,
Keyang

**Comment by beiermosi** [comment]
good,iconv-lite works fine,thanks a lot
