### ISSUE TITLE
Losing leading zeors when converting string to numbers

### ISSUE THREAD

**Issue by Odion100** [Keyang/node-csvtojson#116]
I'm working with a cvs file/string of UPCs. Is there any way to specify that a column should be interpreted as a string?

**Comment by Keyang** [comment]
see https://github.com/Keyang/node-csvtojson#field-type

you can turn off type check with checkType:false

~Keyang

**Comment by rosygupta** [comment]
Even after specifying checkType as false it takes some values as zeroes if the value in the first row is a number.

**Comment by Keyang** [comment]
checkType is now default false
