### ISSUE TITLE
Not working as expected for large CSV files

### ISSUE THREAD

**Issue by bhaskar20** [Keyang/node-csvtojson#117]
Hi,
I'm trying to convert a large csv file, approx 100k rows,
But while converting, the output i'm getting is not as expected

Here is the code: 
var Converter = require("csvtojson").Converter;

```
var csvConverter = new Converter({
    delimiter:";"
});

var fs=require("fs"); 
var csvFileName="./nav.csv";


csvConverter.on("end_parsed",function(jsonObj) {
    console.log(jsonObj);
});

fs.createReadStream(csvFileName).pipe(csvConverter);
```

Output : 
Instead of whole json array i'm getting 5998 more items at the end.
Date: '23-Aug-2016' },
  { 'Scheme Code': 100220,
    'ISIN Div Payout/ ISIN Growth': 'INF192K01528',
    'ISIN Div Reinvestment': 'INF192K01536',
    'Scheme Name': 'JM Balanced Fund-Dividend',
    'Net Asset Value': 10.9772,
    'Repurchase Price': 10.9772,
    'Sale Price': 10.9772,
    Date: '23-Aug-2016' },
  **... 5998 more items ]**

Please help me in getting this resolved
Also, it is working fine in node -v0.36 
but not working in node -v6.3.1

**Comment by Keyang** [comment]
are you saying the console log has "*... 5998 more items *" instead of json
object?

try to change your code likes this:

csvConverter.on("end_parsed",function(jsonObj) {
    console.log(JSON.stringify(jsonObj,null,2));
});


~Keyang

**Comment by bhaskar20** [comment]
Ahh yes, i get it, will try that
Anyway issue is not there will using streams,
I guess that above solution should work, anyway this issue is not in the scope of this library
