### ISSUE TITLE
ISODate type ?

### ISSUE THREAD

**Issue by leizard** [Keyang/node-csvtojson#118]
Hi, thank you for awesome package.
How could I parse to ISODate type ?

When I import:

```
string#!code,createddate,createdbyid,companyid
0000631999391,2016-08-29T06:22:02.164Z,HRvRYKCSy4aXLeZt5,5Zd8dTtSga6TL6jgf
```

it returns 

```
[
  {
    "code": "0000631999391",
    "createddate": "2016-08-29T06:22:02.164Z",
    "createdbyid": "HRvRYKCSy4aXLeZt5",
    "companyid": "5Zd8dTtSga6TL6jgf",
  }
]
```

but I want the result to be

```
[
  {
    "code": "0000631999391",
    "createddate": ISODate("2016-08-29T06:22:02.164+0000"),
    "createdbyid": "HRvRYKCSy4aXLeZt5",
    "companyid": "5Zd8dTtSga6TL6jgf",
  }
]
```

So I can import correctly to my mongodb.
How could I archive that ? 
Thank you very much.

**Comment by Keyang** [comment]
I think you can use transform
https://github.com/Keyang/node-csvtojson#synchronouse-transformer
just simply give a function like:

csvConverter.transform=function (json){
json['createddate']=//do your date text transform here
}

**Comment by leizard** [comment]
Thank you. I have to format my csv before transforming.
