### ISSUE TITLE
Typescript types  (Feature request)

### ISSUE THREAD

**Issue by kc-curefit** [Keyang/node-csvtojson#125]
I would like to use this library in a typescript project. Was unable to find the types on @types/csvtojson

Any plans to publish the types ?

**Comment by EricByers** [comment]
We are using this in typescript as well, and wrote our own quick d.ts  So if that helps:

```
declare module 'csvtojson' {

	import stream = require('stream');

	interface ConverterOptions {
		constructResult?: boolean;
		delimiter?: string | String[];
		quote?: string;
		trim?: boolean;
		checkType?: boolean;
		toArrayString?: boolean;
		ignoreEmpty?: boolean;
		workerNum?: number;
		fork?: number;
		noheader?: boolean;
		headers?: String[];
		flatKeys?: boolean;
		maxRowLength?: number;
		checkColumn?: boolean;
		eol?: string;
	}

	interface StreamOptions {
		objectMode?: boolean; // stream down JSON object instead of JSON array
		highWaterMark?: number; //Buffer level
	}

	export class Converter extends stream.Transform {
		constructor(options?:ConverterOptions, streamOptions?:StreamOptions);
		_read: (size: number) => void;
		fromString(string:string, callback:(err:any, result:any) => void):void;
		fromFile(filePath:string, callback:(err:any, result:any) => void):void;
		on(event:string, callback:Function):this;

		transform: Function;
		preProcessRaw: (data:any, cb:Function) => void;
		preProcessLine: (line:string, lineNumber:number) => void;
	}
}
```

**Comment by kc-curefit** [comment]
thank you

**Comment by wcarson** [comment]
@EricByers this is great. I'd like to clean up/update and publish to Definitely Typed/@types if you don't mind.

**Comment by EricByers** [comment]
@wcarson Yes!  Please do, it's on my checklist to get this in, would benefit everyone.

**Comment by wcarson** [comment]
FYI - I have a PR in to Definitely Typed for this. Updated version of the type definition is here:

[https://github.com/wcarson/DefinitelyTyped/blob/csvtojson/csvtojson/index.d.ts](https://github.com/wcarson/DefinitelyTyped/blob/csvtojson/csvtojson/index.d.ts)

Changes from @EricByers original version:
- In addition to exporting classes/interfaces (i.e. `Converter`, `ConverterOptions`, etc.), it also exports a factory function for a `Converter` so that the library can be used similarly to the examples on the project home page:

```
import { Converter } from 'csvtojson';
const converter = new Converter({noheader: true});

// OR

import * as csv from 'csvtojson';
csv({noheader: true}).fromString(...)...
```

- Added support for event emitter style usage
```
csv({noheader:true})
.fromString(csvStr)
.on('csv',(csvRow) => {
    console.log(csvRow);
})
.on('done', () => {
    //parsing finished
});
```
- Added types for callback function signatures (i.e. `JsonEventHandler`, `CsvEventHandler`, `DoneEventHandler`, etc.)
- JSDoc documentation (mostly blatent cut-n-paste from this site :-)

The definition worked on a couple of my local projects and passed DT's automated tests, so hopefully this is a good start...

**Comment by EricByers** [comment]
Awesome 👍

**Comment by wcarson** [comment]
FYI - type definitions now available on Definitely Typed and npm @types/csvtojson

**Comment by daredkar** [comment]
@wcarson can you tell me how can i use this csvtojson in Angular 2 ; as it is in typescript.

**Comment by wcarson** [comment]
@daredkar 
1. Install - `npm install @types/csvtojson --save-dev`
2. Use
```
import * as csv from 'csvtojson';

// See examples in this project for usage
csv({noheader: true}).fromString(...)...
```

**Comment by daredkar** [comment]
@wcarson i am trying to code as per your suggestion
------------------------code----------------------------------- -
import * as csv from 'csvtojson';

// this function is created for conversion purpose
convertToJson() {
    const csvFilePath = 'app/assets/export.csv';
    const csv = require('csvtojson');
   csv({noheader: true})
      .fromFile(csvFilePath)
      .on('json', (jsonObj: JSON) => {
    console.log(jsonObj);
    })
      .on('done', (error: any) => {
    console.log('end');
    });
  }

-----------------But getting the following error---------------------- 
TypeError: csv is not a function
    at LoginComponent.convertToJson (login.component.ts:57)
    at CompiledTemplate.proxyViewClass.View_LoginComponent0.handleEvent_25 (/AppModule/LoginComponent/component.ngfactory.js:222)
    at HTMLButtonElement.eval (platform-browser.umd.js:3223)
    at ZoneDelegate.invokeTask (zone.js:363)
    at Object.onInvokeTask (core.umd.js:3971)
    at ZoneDelegate.invokeTask (zone.js:362)
    at Zone.runTask (zone.js:166)
    at HTMLButtonElement.ZoneTask.invoke (zone.js:416)

**Comment by wcarson** [comment]
You defined `csv` twice (you don't need `const csv = require('csvtojson');`)

**Comment by daredkar** [comment]
@wcarson i tried by removing `const csv = require('csvtojson');)` no difference same error

**Comment by Keyang** [comment]
@wcarson have you tried update your local @types/csvtojson to latest version?

~Keyang

**Comment by wcarson** [comment]
@daredkar do you have the csvjson library installed (and not just the type definition)?

`npm install csvtojson --save`

**Comment by daredkar** [comment]
Sry for late reply but i have csvtojson (JavaScript) in my project.
but i have not included it in my index.html (is it needed ?)

**Comment by Keyang** [comment]
@daredkar I have created a demo repo showing how to use this lib and `@types/csvtojson` with typescript

**Comment by Keyang** [comment]
Type def is avail through npm:  https://www.npmjs.com/package/@types/csvtojson
This ticket will be closed.

**Comment by ofirnavara** [comment]
@types/csvtojson doesn't work for version 2. Any plans for upgrading?

**Comment by kshrestha99** [comment]
> @types/csvtojson doesn't work for version 2. Any plans for upgrading?

I am hoping for the upgrade for it to work with version 2 as well. I am having issue using it as well.
I have done this: 
`npm i @types/csvtojson -D`

In my typescript file:
`import * as csvtojson from 'csvtojson';

csvtojson().fromFile(csvFilePath)`

In my console: 
Error Message: Error: TSError: ⨯ Unable to compile TypeScript:
someTypeScriptFile.ts:35:11 - error TS2349: This expression is not callable.
  Type '{ default: (param?: Partial<CSVParseParam>, options?: TransformOptions) => Converter; }' has no call signatures.

**Comment by shaniqwa** [comment]
i'm getting the same error as @kshrestha99
