### ISSUE TITLE
preProcessLine hook

### ISSUE THREAD

**Issue by iuriiAulikh** [Keyang/node-csvtojson#128]
Hi 
Thanks for such great module. It seems like in version 1.1.0 ['preProcessLine' ](https://github.com/Keyang/node-csvtojson/blob/master/dist/csvtojson.js#L294) hook is never used. Will it be removed in future version or it is a bug?
Thanks, Iurii

**Comment by Keyang** [comment]
Hi,
Thanks for using csvtojson.
It is bug. I will fix it soon.
Thanks for pointing it out.
1.1.0's API should contain all old APIs which will not be deprecated.

Regards,
Keyang
