### ISSUE TITLE
"End" or "end_parsed" not triggered when checkColumn: true

### ISSUE THREAD

**Issue by pdinesh80** [Keyang/node-csvtojson#129]
I'm facing an issue, when I use "checkColumn: true", end or end_parsed is not emitted. I do see errors for the records (on error) not parsed correctly. But need "end" event to do the response.

If i remove checkColumn I see End/End_parsed getting triggered.

Please advise if I'm missing anything.

**Comment by Keyang** [comment]
Since 1.1.1, using 'done' event will guarantee being emitted it is finished as 'end' will only be emitted if there is no data to consume
https://github.com/Keyang/node-csvtojson#done
