### ISSUE TITLE
Hex numbers in CSV parse to 0 

### ISSUE THREAD

**Issue by chatch** [Keyang/node-csvtojson#130]
The hex numbers in the following csv file parse to '0' and the rest is skipped:

"account_address","display_name"
0x15a97504f6f678ab11a88241a6518661803ed667,"Account 1"
0x8c2ca08823e5cc47fcb63bc173864741cd7ff27e,"Account 2"

results in : 

{"account_address":0,"display_name":"Account 1"},{"account_address":0,"display_name":"Account 2"}]

I tried surrounding the hex in quotes too but the result is the same. Seems there some special processing of 'x' or '0x'

NOTE: Works in 1.1.0, fails in 1.1.1

**Comment by Keyang** [comment]
Thanks for the reply. I will fix it soon.

**Comment by Keyang** [comment]
For a temporary solution, you could try to set checkType:false

~Keyang

**Comment by Keyang** [comment]
fix in 1.1.2
