### ISSUE TITLE
flatKeys setting being ignored

### ISSUE THREAD

**Issue by arrow-mjanisse** [Keyang/node-csvtojson#131]
Upgrading my project to v1.1.1 seemed to produce a regression where headers containing periods were being processed as if they were in object notation.  Reverting my project to v1.1.0 resolved the issue, so it appears to be a regression in just the last update.

Please let me know if there is any more information you'd like to know.

**Comment by Keyang** [comment]
Thanks for letting me know. I will fix this soon.

~Keyang

**Comment by atufkas** [comment]
Same issue here - just broke my installation after upgrading to 1.1.1. Thanks for fixing anyway. When will you probably come up with a 1.1.2?

Regards,
Matthias

**Comment by Keyang** [comment]
I think currently latest version in npm is 1.1.2?

~Keyang

**Comment by atufkas** [comment]
I'm sorry, my mistake - you're right!
