### ISSUE TITLE
synchronous

### ISSUE THREAD

**Issue by miniil** [Keyang/node-csvtojson#136]
Hi.  First thanks for this module.

How can we get the json object without listen the event end_parsed and how can I get this object before continuing (synchronous).

Thanks for your response

**Comment by Keyang** [comment]
You cannot. Node.js suggests all modules being async.
You will need to coordinate your code like this:

csv()
.on('end_parsed',(data)=>{
 // your other code

})


this will look better with es7 await / async syntax.
~Keyang

**Comment by WORMSS** [comment]
I too needed this to be synchronous. Its a real shame as the rest of the api looked good.

**Comment by rayfoss** [comment]
@WORMSS You could use v1...

darn it... I have a deep stack that will need to be refactored to support async. Lesson learned the hard way. Use async on your modules... even if you don't need it.
