### ISSUE TITLE
Space before comma removed while conversion

### ISSUE THREAD

**Issue by rosygupta** [Keyang/node-csvtojson#143]
While uploading and converting the csv file to json using csvtojson, the space before a comma character is automatically removed. 

eg. Sample Text , Here 

gets converted to==>

Sample Text, Here

**Comment by Keyang** [comment]
Hi,
You need to pass in `trim:false` or `--trim=false` in cli to reserve the spaces.

~Keyang

**Comment by rosygupta** [comment]
@Keyang  Please specify where in cli?

**Comment by Keyang** [comment]
Hi,
If you type `csvtojson --help` in cli, you can see the `--trim` option in help list.

~Keyang

**Comment by rosygupta** [comment]
Thanks! That worked (y)
