### ISSUE TITLE
Reading header of CSV-file

### ISSUE THREAD

**Issue by tom-heyvaert** [Keyang/node-csvtojson#146]
I am looking for the fastest way to read the header of a CSV-file without reading the rest of the file.

**Comment by tom-heyvaert** [comment]
After some trial and error I came up with following solution.

`		var preview = [];

		var stream = fs.createReadStream('./uploads/' + file)
			.pipe(
				csv({ 
					delimiter: 'auto',
					trim: true
				})
			)
			.on('json',function(jsonObj, index) {
				if(index <= amount) {
					preview.push(jsonObj);
				} else {
					stream.end();
				}
			})
			.on('done', function(err) {
				callback(preview);
			})`
Parses X amount of CSV-rows and returns them parsed as json in the callback.

**Comment by Keyang** [comment]
you can use noHeader:true with 'csv' event. the first call back is the
header row

csv({noHeader:true}).on('csv',function(row,idx){})

~Keyang
