### ISSUE TITLE
What files are necessary for browser usage ?

### ISSUE THREAD

**Issue by stla** [Keyang/node-csvtojson#153]
Hello,
First, thank you for this nice library.
 If I want to use `csvtojson` in the browser, which files are necessary ? `csvtojson.min.js` is not enough. I think I can delete the `bin` folder, and what else ?

**Comment by Keyang** [comment]
Hi,
I use
https://cdn.rawgit.com/Keyang/node-csvtojson/e963d121/dist/csvtojson.js
in http://keyangxiang.com/csvtojson/

~Keyang

**Comment by stla** [comment]
This file is enough but not the `min.js` ?
Thank you, I will try.

**Comment by stla** [comment]
Indeed, this works. Thanks!
