### ISSUE TITLE
done event is called twice

### ISSUE THREAD

**Issue by chanakyap** [Keyang/node-csvtojson#156]
I have a csv file with content as 
`"a","b", "c""`
when i parse this, done is called twice, once with error, once without error. I am assuming the second time is because of the end event, but is there anyway that done is called only once in this case?

**Comment by Keyang** [comment]
Hi,
Thanks for feedback. I would think it is a bug. for now you can use
following workaround:
csv()
.once('done', handler)

this will guarantee the handler been called only once...

~Keyang

**Comment by Kannas24** [comment]
The entire execution cycle is wrong. 
colParser function not even firing

sequence is 
then() -> "done" and if I add "once" instead of "on" as suggested by @Keyang  then my colParser function is not even getting triggered.
