### ISSUE TITLE
how to pass unclosed_quote error

### ISSUE THREAD

**Issue by Primary-Traxex** [Keyang/node-csvtojson#161]
line likes:
`"23333","464654',"8989898"`
the 464654 will raise a error and csvtojson emit end event

**Comment by Keyang** [comment]
The suggestion is to use `preFileLine` hook to correct the line which contains the issue. (see [preFileLine hook ](https://github.com/Keyang/node-csvtojson#csv-file-line-hook) )
The difficulty of passing an error is parser cannot tell if a quote will or will not close until end of the csv stream.And once it reaches the end, it is not possible to come back to where it has problems to pass it.

~Keyang

**Comment by Primary-Traxex** [comment]
hi Keyang
The suggestion seems can not work in CLi
anyway, thank you!

**Comment by Primary-Traxex** [comment]
when i trying to solve the problem i find a solution.
i use sed. like this:
`sed -i '/some matching character$/{N;s/\r\n//}' yourfile`
`-i    >operate real `file``
`/some matching character$/`    >matching the character in the `end`
`{N;s/\r\n//}`    >if match run the code
`N`    >put the match line to module space
`s/\r\n//`    >then replace `\r\n` to null
sed run in lines so he can't recognize \n character so i use N,it can put lines into module space.
if your file isn't too big , you can also use N at first ,that means you put all lines into module space.
in the end ! sed very faster 运行速度非常快
