### ISSUE TITLE
Chinese word convert issue

### ISSUE THREAD

**Issue by shazidama** [Keyang/node-csvtojson#167]
When i convert my JSON  to CSV, if the header is chinese word, it will become garbled. This really confuse me.

**Comment by Keyang** [comment]
Could you give an example which causes your problem?
the parser should work under utf8 encoding which should support Chinese words no problem.

~K

**Comment by shazidama** [comment]
Maybe i use wrong method dealing with Chinese word, now i can work it in right way.
3q~

**Comment by shazidama** [comment]
i use the code like below,
//const csv=require('csvtojson')
//csv()
//.fromFile(csvFilePath)
//.on('json',(jsonObj)=>{
//  console.log(jsonObj)
//})
//.on('done',(error)=>{
//	console.log('end')
//})
my csv is like below
地区,电话数,程序数,网购数,总数
北京市，100,200,300,400
石家庄,101,201,301,401
天津市，2,2,2,2
唐山市3,3,3,3

**Comment by Keyang** [comment]
Hi,
It looks like your csv data mixed Chinese comma with normal commas. I would suggest you to process your data with following code:
```js
const csv=require('csvtojson')
csv()
.preRawData((csvRawData,cb)=>{
	var newData=csvRawData.replace('，', ',')
	cb(newData);
})
.on('json',(jsonObj)=>{

});
```
You will need to keep your delimiter consistent across the csv data.

~Keyang

**Comment by lovelyorg** [comment]
我也遇到了乱码的问题, 
最后发现csv文件的编码为GB2312, 编码改为UTF8不乱码.
