### ISSUE TITLE
csvtojson isn't working in Express middleware

### ISSUE THREAD

**Issue by dtsellos03** [Keyang/node-csvtojson#170]
I am using csvtojson to convert an uploaded CSV  to JSON via the function Middleware:

```
app.post('/profile', upload.single('inputcsv'), function (req, res, next) {
  var filepath = req.file.filename;
  Middleware(filepath, "TEST.json");
  res.send("Success");
})

function Middleware(filepath, outputname){
    var fullpath = "uploads/" + filepath;
    var readStream = fs.createReadStream(fullpath);
    var writeStream = fs.createWriteStream(outputname);
    readStream.pipe(csvConverter).pipe(writeStream);  
}
```
The issue is that the outputted JSON file resulting from a POST request is empty. If I pass a csv that already exists on the server (not the one submitted in the post request), it still outputs an empty JSON.

But when I call Middleware outside of the app.post(....) environment, it works properly. Any ideas on why it won't work inside the POST route? My goal is to further process the JSON file within the route.

**Comment by Keyang** [comment]
you need check following:
1. the uploaded file "inputcsv" from upload.single middware does create
file and contains csv data.
2. try return success after your process finished. In code you send, the
post route finished before the actual process starts.

~Keyang

**Comment by dtsellos03** [comment]
Thanks for the quick reply! I After trying those suggestions (checking the uploaded csv, and adding a return statement to the middleware), I could not get the 

```
var readStream = fs.createReadStream(fullpath);
var writeStream = fs.createWriteStream(outputname);
readStream.pipe(csvConverter).pipe(writeStream);  
```
methods to work inside the post route (even if the input csv already existed on the server). However, the following works for me (jsonObj is the correct output):

```

function Middleware(filepath, outputname){
    var fullpath = "uploads/"+filepath;
    const csvFilePath = fullpath;
    const csv = require('csvtojson');
    csv()
    .fromFile(csvFilePath)
    .on('json',(jsonObj)=>{
        console.log(jsonObj);
    })
    .on('done',(error)=>{
        console.log('end');
    })
}
```

My only remaining question is how do I access jsonObj outside of the stream (I can't push jsonObj to an array)? Do I need to create a fs.createWriteStream?  I am a beginner with streams, sorry if this is a simple question. I have tried return statements to retrieve jsonObj or jsonArray (when using toArrayString option) but the output is always empty/undefined. Thanks again for your support!

**Comment by Keyang** [comment]
ok. you have to call the `csv()` as a function first to init an instance.

`csv().fromFile` creates a `Writable stream`  so you do not need to create your own.

to use stream you can try following code:

```js
csv()
.fromFile(csvFilePath)
.pipe(writeStream)

```

~Keyang

**Comment by dtsellos03** [comment]
Thank you for the helpful information, this works for me.
