### ISSUE TITLE
Not getting proper data while using stream

### ISSUE THREAD

**Issue by mmohtta** [Keyang/node-csvtojson#173]
Hi ,
I am using stream option to parse my csv , csv is provided as a stream dowloaded from mongodb (GridFSBucketReadStream) . But it gives all data in binary in events of trasf,json and csvrow.
Please suggest if i'm doing something wrong

**Comment by mmohtta** [comment]
![image](https://cloud.githubusercontent.com/assets/27994083/26494334/d77d91f8-423b-11e7-9a9e-cf304275846f.png)

**Comment by mmohtta** [comment]
![image](https://cloud.githubusercontent.com/assets/27994083/26494353/f159aa80-423b-11e7-99ae-826585b646ee.png)

**Comment by mmohtta** [comment]
![image](https://cloud.githubusercontent.com/assets/27994083/26494691/88034616-423d-11e7-83fd-d830b78fa666.png)
Value in jsonObj in transf event

**Comment by Keyang** [comment]
not seeing a particular issue.
try to debug `stream.on("data",(d)=>{debugger;})`
see whats coming out of  original stream..

**Comment by mmohtta** [comment]
data is correct because when i parse the stream and pipe the data in a file its working
downloadStream.pipe( fs.createWriteStream(`${__dirname}/../${zipPath}`) );

**Comment by mmohtta** [comment]
Previously i was parsing from same code for file ... i was getting the file through same stream code ...
saving it in a file and then giving the csvtojson library path of that file
that time its working
But when i directly pass the stream to the library i'm getting issues

**Comment by Keyang** [comment]
i think it is todo with data encoding as parser assumes upstream encoding is `utf8`

**Comment by mmohtta** [comment]
nope , i have tried ot by setting the stream encoding to utf8 then also its not working

**Comment by Keyang** [comment]
what downlaod module u r using? i'll try to recreate this.

**Comment by mmohtta** [comment]
i uploaded the file in mogodb gridfs 
and download code i have sent in first image
and then passed it to csvtojson library

**Comment by mmohtta** [comment]
![image](https://cloud.githubusercontent.com/assets/27994083/26495598/d89ad964-4241-11e7-8bfd-9e8bb767207e.png)
See previously i was doing it in this was

**Comment by mmohtta** [comment]
![image](https://cloud.githubusercontent.com/assets/27994083/26495717/499a9500-4242-11e7-8daf-553f73d302e6.png)
this is upload code

**Comment by Keyang** [comment]
Thanks. I will take a look. also could you please tell me what version of `csvtojson` you are using?

**Comment by mmohtta** [comment]
1.1.5

**Comment by kishe89** [comment]
Has this problem been resolved? i have a same issue.

Please look at the code below

```javascript
const parser = require('csvtojson');
const Iconv = require('iconv').Iconv;
const iconv = new Iconv('euc-kr','utf-8//translit//ignore');
const fs = require('fs');
const csvFilePath='./csv/store/store_201706_02.csv';
parser().fromStream(fs.createReadStream(csvFilePath))
                .on('json',(data)=>{
                    //data is a buffer object
                    // console.log(data);
                    let utf8string = iconv.convert(data).toString();
                    console.log(utf8string);
                })
```
It does not work great when I try to change the buffer encoding.

this csv file encoding type is EUC-KR.

```javascript
let buffer = fs.readFileSync(fd);
const Iconv = require('iconv').Iconv;
const iconv = new Iconv('euc-kr','utf-8//translit//ignore');
const string = iconv.convert(buffer);
fs.writeFile('test.csv',string,function () {
    console.log('done');
});
```
The above code works. What is the difference between the buffer obtained from the above code and the buffer obtained from the csvtojson module?

Please suggest if i'm doing something wrong

**Comment by Keyang** [comment]
You need convert the data to utf8 before it reaches the parser.
As parser will assume only 2 type of data input 1- utf8 string and 2- utf8 buffer.
Any other encoding is not supported.

**Comment by kishe89** [comment]
Thank you. I solved it
