### ISSUE TITLE
ignore all datatypes and retain the values in  quotes

### ISSUE THREAD

**Issue by rajashekhargundeti** [Keyang/node-csvtojson#176]
Hi,

Numeric data is being detected and when converted to json , it is not having quotes.

My requirement is : business data order numbers are having leading zeros in the data, like, 0001, 0012.
When converted to json, the values are becoming 1 and 12 respectively.

Please let me know how to avoid this and retain the data as it is.

--Rajashekhar

**Comment by Keyang** [comment]
you could use `checkType:false` parameter to turn off the data type detection..

~Keyang

**Comment by rajashekhargundeti** [comment]
Please correct the documentation:
checkType: This parameter turns on and off whether check field type. Default is false.
