### ISSUE TITLE
keep value with leading 0 as string

### ISSUE THREAD

**Issue by dciccale** [Keyang/node-csvtojson#181]
hi, in 0.x version I was converting some csv like this

```
id,phone
3,015124718364
```

into:

```json
{
  "id": 3,
  "phone": "015124718364"
}
```

Notice the `"id"` is a `Number` and the `"phone"` is a `String` which is my desired output.

However, on version 1.1.6 with `checkType: true` I am getting this:

```json
{
  "id": 3,
  "phone": 15124718364
}
```

Notice that the leading 0 of the phone is gone. and both are numbers now.

How could I keep the phone as a `String` but not other numbers? Would make sense to have some option for leading 0s or should I set `checkType: false` (default) and do formatting myself? (not my desired solution though)

Any thoughts on how to achieve this? Thanks in advance

**Comment by Keyang** [comment]
I would consider this as a enhancement of current type inference.
But if you need solution now you can use explicit type by re-defining the headers
```js
csv({
    headers:['id','string#!phone']
})
```
The explicit type feature is not documented in version 1.0.0+ but it can be used 
https://github.com/Keyang/node-csvtojson/blob/develop/readme-old.md#explicit-type

~Keyang

**Comment by Keyang** [comment]
Feature:
need to customise type inference logic
