### ISSUE TITLE
Can't resolve 'fs',  Can't resolve 'child_process

### ISSUE THREAD

**Issue by sudheerDev** [Keyang/node-csvtojson#183]
Hello I get these errors when using node-csvtojson. I want the library for conversions on browser .

      ERROR in ./~/csvtojson/libs/core/Converter.js
       Module not found: Error: Can't resolve 'fs' in '/Users/sudheer/Documents/work/dataglen-
        frontend/node_modules/csvtojson/libs/core'
     @ ./~/csvtojson/libs/core/Converter.js 473:11-24
     @ ./~/csvtojson/libs/core/index.js
     @ ./~/csvtojson/libs/csv2json.js
     @ ./~/csvtojson/index.js
     @ dll reactBoilerplateDeps

    ERROR in ./~/csvtojson/libs/core/workerMgr.js 
     Module not found: Error: Can't resolve 'child_process' in 
     '/Users/sudheer/Documents/work/dataglen-frontend/node_modules/csvtojson/libs/core'
     @ ./~/csvtojson/libs/core/workerMgr.js 2:12-36
     @ ./~/csvtojson/libs/core/Converter.js
     @ ./~/csvtojson/libs/core/index.js
     @ ./~/csvtojson/libs/csv2json.js
     @ ./~/csvtojson/index.js
     @ dll reactBoilerplateDeps

This helped me solve the errors though. https://github.com/webpack/webpack/issues/744

Should this be part of package.json in csvtojson by default?

**Comment by Keyang** [comment]
for now you can use `dist/csvtojson.js` file in a `<script>` tag. once imported, you can use `csvtojson` from `window`. The client lib is built with latest `csvtojson`

I will get this fixed soon.

~Keyang

**Comment by puXiaoyi** [comment]
waiting for v 1.18 to fix " Module not found: Error: Can't resolve 'child_process' in ...." bug

i can't use csvtojson in react web project

**Comment by Jonarod** [comment]
Same thing here. Can't use the project...
I tried either one of:
```
import csv from 'csvtojson';
// or
import csv from 'csvtojson/dist/csvtojson.min.js';
```
gives errors:
`Module not found: Error: Can't resolve 'fs'`
or 
`Uncaught TypeError: Cannot read property 'split' of undefined`
