### ISSUE TITLE
Output from csvtojson not pure JSON

### ISSUE THREAD

**Issue by ateev** [Keyang/node-csvtojson#184]
I'm trying to use this tool to convert a csv to JSON. The output i'm getting is not exactly pure "JSON".

What I tried:

```
var csvToJson = require('csvtojson');
const converter = csvToJson({
  ignoreEmpty: true,
});

csvToJson()
  .fromFile(csvFile)
    .on('json', function(jsonObj) {
      console.log(jsonObj);
     })
    .on('done', function() {
      console.log("done !");
    });
```
 
And the output was something like this:

```
{ 
  field1: '100051',
  Membership: '100051',
  gender: 'male',
}
```

And what i'm expecting:

```
{ 
  "field1": "100051",
  "Membership": "100051",
  "gender": "male",
}
```

So i'm expecting is quotes around the object keys, which is the standard JSON. How can i achieve that ?

Thanks in advance :)

**Comment by Keyang** [comment]
the jsonObj is pure JSON object...
I think you need strigified JSON object so you can do this:

console.log(JSON.stringify(jsonObj));

~Keyang

**Comment by ateev** [comment]
@Keyang Thanks for quick reply. That solved the problem. But shouldn't that be out of the box ?

https://stackoverflow.com/questions/949449/json-spec-does-the-key-have-to-be-surrounded-with-quotes

**Comment by Keyang** [comment]
It is because `console.log` function you used does not print the quotes -- you can try with other `JSON Object` in javascript and `console.log` will never print the quotes.

**Comment by ateev** [comment]
Ah gotcha !  Thanks. Closing this.

**Comment by jfr3000** [comment]
I am having the same problem. The output from `csvtojson()` cannot be parsed as JSON. The thing about `console.log` is also not quite right:
![image](https://user-images.githubusercontent.com/9396227/43769038-1ba2424c-9a39-11e8-83dc-67883c38ea46.png)

It seems like maybe you are equating Javascript objects with JSON? In any case, this:
```
csvtojson().fromString('name, age\njane,doe').then(result => JSON.parse(result))
```
will throw an error `Unexpected token o in JSON at position 1`, proving that the result is not in fact JSON.
