### ISSUE TITLE
flatKeys not working

### ISSUE THREAD

**Issue by popod** [Keyang/node-csvtojson#190]
It seem that flatKeys not working as expected.

```
    let options = {
      delimiter: [';', ',', '\t'],
      headers: [
        'a'
        'b.c'
      ],
      flatKeys: false
    }

    csv(options).fromFile(csvFilePath).on('json', jsonData => {
      console.log(jsonData)
    })
```

`jsonData.a` is define but `jsonData.b.c` is not defined !

**Comment by popod** [comment]
@Keyang please any news about this ?

**Comment by Keyang** [comment]
Hi,
Are you looking for jsonData["b.c"] or jsonData.b.c ?

~Keyang

**Comment by popod** [comment]
`jsonData.b.c` like this object:
```
jsonData = {
  a: {
    b: "value"
  }
}
```

**Comment by Keyang** [comment]
Hi 
I just tested with v1.1.7 
```
echo  "1,2" | csvtojson --headers='["a","b.c"]' --noheader=true
[
{"a":"1","b":{"c":"2"}}
]
```

isnt this what you want?

~Keyang

**Comment by popod** [comment]
Yes, this is exactly what I want ! I've make more tests and this seems that this works now.. Thanks for you help and sorry !

**Comment by Keyang** [comment]
no problem.
