### ISSUE TITLE
parse fail if the col content end with double quote

### ISSUE THREAD

**Issue by chikchoi6** [Keyang/node-csvtojson#196]
For example,
the csv is "abcdef","abcdef","abc"def"","abcdef"
the result will be 
[
  {
    "field1": "abcdef",
    "field2": "abcdef",
    "field3": "abc\"def\",\"abcdef"
  }
]

But the correct result should be 
[
  {
    "field1": "abcdef",
    "field2": "abcdef",
    "field3": "abc\"def\"",
    "field4": "abcdef"
  }
]

**Comment by Keyang** [comment]
according to csv format standard if a double quote is needed in a quoted column the double quote need to be escaped by another double quote. so the 3rd column should be like "abc""def"""

http://www.creativyst.com/Doc/Articles/CSV/CSV01.htm#FileFormat

**Comment by Keyang** [comment]
This is now supported with version 2+
