### ISSUE TITLE
Lowercase header row names to support consistent object keys

### ISSUE THREAD

**Issue by lafama** [Keyang/node-csvtojson#202]
Is it possible to have the header row values converted to lowercase to support the following scenario
This csv will have a different output
```
Names,age,Family
John,50,My family
```

To this csv file
```
names,Age,family
John,50,My Family
```
The json generated will have different object keys in both cases because of the header row naming.
```
1.{Names:John,Age:50,Family:My Family}
2.{names:John,age:50,family:My Family}
```

**Comment by Keyang** [comment]
You can specify `headers` in parameter with alll lower case headers.
or
you can write a hook for first line like below:
```js
csv(csvFile)
. preFileLine((fileLine,idx)=>{
    if (idx === 0 ){return fileLine.toLowerCase();}
return fileLine;
})
```

**Comment by mhonnatti** [comment]
@Keyang  Does `preFileLine` work on source csv from files only? I'm using stream and wanting to convert header row to lower case.

**Comment by Keyang** [comment]
no not only for files but also for other type of csv data source
