### ISSUE TITLE
Wrong encoding when loading UTF-8 csv file.

### ISSUE THREAD

**Issue by felzend** [Keyang/node-csvtojson#209]
Hi, I'm having an issue related to encoding.
My Worksheet is in UTF-8 encoding, but when I read it in nodejs, it's shown broken like below:

Original Text:  **Ajuste de horário.**
Shown Text:  **_Ajuste de hor�rio._**

How do I fix this?

Thanks.

**Comment by Keyang** [comment]
What version of csvtojson you are using?

**Comment by felzend** [comment]
"csvtojson": "^1.1.9"

**Comment by felzend** [comment]
I discovered the .csv file I get is generated by an old system, so it might be bugged related to encoding.
It's not really a problem with your package, but would be good if it was able to read this kind of csv files.
So I've done this and now it reads fine when loading. Shouldn't be the best performatic solution, but I guess that's what can be done.

**iconv file1csv -f latin1 -t utf-8 -o file2.csv**

**Comment by Keyang** [comment]
Glad your sorted this out.
Encoding is a frequently asked question. Could possibly add a section in README for this.
