### ISSUE TITLE
Wrong index with preFileLine hook

### ISSUE THREAD

**Issue by magiksd** [Keyang/node-csvtojson#210]
Hi, I'm trying to use the "preFileLine" hook with a file stream using "fromFile", but when using "console.log" to display arguments of the "preFileLine" callback, I can clearly see the same line number for 2 different line data, for me it's at line 1166 but maybe it can change depending of data chunk coming from the stream, I've used a 143 Ko CSV file with 2760 lines.

By the way, why is there an index difference between "preFileLine" hook and "csv" callback ? The first starts at 1 and the second starts at 0, which is not consistent.

**Comment by Keyang** [comment]
Should have it fixed in v2.0.0
