### ISSUE TITLE
How to add columns? 

### ISSUE THREAD

**Issue by matbz** [Keyang/node-csvtojson#215]
My csv file has 9 columns but 10 values. I want to add 1 column manually before parsing the file. How can I achieve this? Thanks!

**Comment by Keyang** [comment]
You could specify the columns manually in `headers` parameter.
https://github.com/Keyang/node-csvtojson#parameters

**Comment by matbz** [comment]
The first nine column are dynamically set (there are different csv templates for my use cases - some with matching columns/values and some like in the above example) so I would only need add one generic "extra" column. Is this possible?

**Comment by Keyang** [comment]
Yeah there are couple ways.
1. csvtojson will automatically add a `field10` key to the json for the column has no header.
2. you can use `header` event which would return header row. where you could append a header you want at that stage.

~Keyang

**Comment by matbz** [comment]
Thank you!
