### ISSUE TITLE
Does not work with React-Native: relies on http module

### ISSUE THREAD

**Issue by TheGitLife** [Keyang/node-csvtojson#219]
In React-Native, I keep getting the error:
"Unable to resolve module `http`

When I try to install https://www.npmjs.com/package/http via 'npm install http', I get an empty folder with package.json file. 

Any idea how to resolve this?

**Comment by Keyang** [comment]
This is caused by a deprecated feature which will be removed in next version

**Comment by Keyang** [comment]
Removed depency of `http`
