### ISSUE TITLE
Sync API methods

### ISSUE THREAD

**Issue by GianCastle** [Keyang/node-csvtojson#223]
Do you have any plans on implement sync methods?

Best rewards!

**Comment by Keyang** [comment]
Hi,
We are going to support `async` and `await` for ES7
Does this solve your issue?

~Keyang

**Comment by GianCastle** [comment]
Yes indeed!

**Comment by realshaft** [comment]
Hi Keyang,

do you already know when this is going to be supported? Thanks.

**Comment by krisnamargono** [comment]
Hi @Keyang, is `async` `await` supported already?

**Comment by Keyang** [comment]
Supported since v2.0.0
