### ISSUE TITLE
Set header row to e.g. 5th row?

### ISSUE THREAD

**Issue by matbz** [Keyang/node-csvtojson#230]
First of all: Thank you for this amazing project. I love it!

Problem: The header row is the 5th row of the csv.

So I would need to remove row 1-4. How can I achieve this? I thought about the oreFileLine hook but I don't know how I can actually remove a line with that: return '' obv. doesnt work.

Thank you!

**Comment by alperdemirci** [comment]
I have the same issue, I would like to set the headerRow number as well.

**Comment by alperdemirci** [comment]
Ok so I found a solution that I am not sure if it is ideal but here my workaround by using a hook;

converter.fromFile(`${__dirname}/example.csv`,function(err,result){
            if(err){console.log("Error", err); }
            console.log('result ', result); //here is the result 
        }).preRawData((csvRawData,cb) => {
            for(var i=0;i<HeadlineRowNumber-1;i++) {
                csvRawData = csvRawData.substring(csvRawData.indexOf("\n") + 1);
            }
            cb(csvRawData)
        }).on('json', (jsonObject) => {
                console.log('jsonObject ', jsonObject)
            })

so what happens here is that I find the raw string (with .preRawData hook)  before processing the json I look for the "\n" and remove the lines that I don't need it. One can improve this solution and if you find something better please post here!! 
Good luck!!!

**Comment by Keyang** [comment]
yeah use preFileLine hook could help you to remove / control raw data with wanted changes.

**Comment by SpencerKaiser** [comment]
@Keyang this would be an awesome addition to the `csv` options parameter... I would love to instantiate like this: 
``` javascript
const data = async csv({headerRow: 5}).fromFile(dataFilePath);
```
Would you consider adding that?
