### ISSUE TITLE
early return

### ISSUE THREAD

**Issue by danacalcaianu** [Keyang/node-csvtojson#235]
Is it possible to early return from a hook? For example for validation purposes, if I have some conditions on a .on('json') hook and I don't want to go further to the next hooks. Or maybe to have a flag that indicates that something is wrong.

**Comment by Keyang** [comment]
Generally this is where you need to use pipe.
You write a Writable in which it will populate json objects along side with
a callback allowing you to send errors.
once you have the Writable, u can simply
csv().fromFile(path).pipe(yourWritable)
