### ISSUE TITLE
Getting auto detected delimiter and eol

### ISSUE THREAD

**Issue by gabegorelick** [Keyang/node-csvtojson#252]
`csvtojson` can infer delimiter, eol, and headers. The inferred headers are returned on `header` or `json` events. But is there a way to get back the delimiter and end of line sequence that were detected?

**Comment by gabegorelick** [comment]
This works:
```js
const csv = require('csvtojson');
const parser = csv({delimiter: 'auto'})
  .fromStream(...); // or from wherever

console.log(parser.param.eol);
console.log(parser.param.delimiter);
```

It this stable API though?

**Comment by Keyang** [comment]
no it is not stable API or even an API...
In fact, I am changing this right now :), as mutating incoming parameters is not a good practice.

I will expose `eol` and `delimiter` events in verison `2.0.0`

For now, you could use the code below:
```js
const csv = require('csvtojson');
const parser = csv({delimiter: 'auto'})
  .fromStream(...) // or from wherever
  .on("header",function(){
     console.log(parser.param.eol);
     console.log(parser.param.delimiter);
  })

```

But this approach will not work in `2.0.0`

**Comment by gabegorelick** [comment]
@Keyang Any idea when 2.0 will be ready? If it won't be for a while, does it make sense to implement `eol` and `delimiter` events in the current release? Even if they just emit `parser.param.eol` and `parser.param.delimiter`, that would allow clients on 1.0 to start using the correct API now.

Let me know if I can help.

**Comment by Keyang** [comment]
hmm.. `2.0.0` is a complete rewrite in Typescript thus it wont be ready in short term.
If you need this feature now, my suggestion for you is to fork this repo and make changes like above.
If you want npm being updated, send me a PR and I could release a `1.1.10` once all tests passed.

**Comment by lukaschoebel** [comment]
In case anyone is wondering how to parse the auto detected delimiters from a csv file in the current version, I found it quite convenient do to it as follows and react to the emitted event:

```typescript
import csv from 'csvtojson';

function getParser(content: string) {
 
  const parser = csv({
    output: "csv",
    delimiter: "auto",
  }).fromString(content);

  parser.on("delimiter", () => {
    console.log(parser.parseRuntime.delimiter as string);
  }) 
}
```
