### ISSUE TITLE
benchmark.js missing in bin

### ISSUE THREAD

**Issue by lajpatshah** [Keyang/node-csvtojson#260]
Earlier version of this package had benchmark.js in the bin folder.

Now that file is missing & because of that package has stopped working. 

Please help

**Comment by Keyang** [comment]
Hi
what error you got?

~Keyang

**Comment by lajpatshah** [comment]
Hi

the function converter.fromString() did not execute only cause that function is written in benchmark.js

We had old version of your package in which the code was working but when we were deploying on our server our code did not gave required output. On checking the issue we found that in current version benchmark.js file is missing and it had converter.fromString() written in it.

thanks
lajpat

**Comment by Keyang** [comment]
Hi 
`converter.fromString` is defined in `Converter` class which is in `Converter.ts` file
https://github.com/Keyang/node-csvtojson/blob/master/src/Converter.ts#L58
Would you copy over the error stack you see in the console?

~Keyang
