### ISSUE TITLE
Async / await issue?

### ISSUE THREAD

**Issue by wwwork** [Keyang/node-csvtojson#263]
Trying to get converted to json string with node-csvtojson. Why node-csvtojson do not return converted to json string at async mode?

Code example 
```
modeule.exports = async (req, res, next) => {
const strindWithDelimiter='bla;bla;bla'
const csv=require('csvtojson')
// Async / await usage
const jsonArray=await csv().fromString(strindWithDelimiter);
console.log( jsonArray); <--- receive empty object wtihs node-csvtojson custom options
}
```

**Comment by Keyang** [comment]
Hi,
What version of csvtojson you are using?
Also are you using es7 or typescript?

~Keyang

**Comment by wwwork** [comment]
es7,
"csvtojson": "^1.1.9"
