### ISSUE TITLE
skip two rows when setting noheader: false

### ISSUE THREAD

**Issue by andrew781026** [Keyang/node-csvtojson#266]
i use csv below , and want to replace header with 

[PatLog - 2018-06-14 12_04_45.zip](https://github.com/Keyang/node-csvtojson/files/2163539/PatLog.-.2018-06-14.12_04_45.zip)

const patLogHeaders = [
    'exam_date', 'sample_no', 'status', 'sample_type', 'patient_id', 'last_name', 'first_name', 'gender_of_patient',
    'patient_birth_date', 'patient_note', 'patient_department', 'accession_number', 'sample_site', 'physician', 'operator',
    'department', 'note', 'test_order_code', 'draw_time', 'approval_status', 'approval_time', 'report_layout',
    'patient_account_number', 'none_1', 'errors_detected_during_measurement', 'age', 'error_code_01', 'weight', 'error_code_02',
    'height', 'error_code_03', 'hcg_beta_p', 'error_code_04', 'troponin_i_p', 'error_code_05', 'ck_mb_p', 'error_code_06',
    'd_dimer_p', 'error_code_07', 'hscrp_p', 'error_code_08', 'myoglobin_p', 'error_code_09', 'nt_probnp', 'error_code_10',
    'crp', 'error_code_11', 'bnp', 'error_code_12', 'tnt', 'error_code_13', 'demo_p', 'error_code_14', 'pct', 'error_code_15'
]; 

when i get json use csv().fromFile , i got a jsonArray with skip 2 rows ( header row + first data row ) ,
how can i do to fix this problem ?

**Comment by andrew781026** [comment]
i put the csv file into the PatLog - 2018-06-14 12_04_45.zip , you can down load and unzip it

**Comment by andrew781026** [comment]
can you zip the  PatLog - 2018-06-14 12_04_45.zip , or i needto do any thing ?

**Comment by Keyang** [comment]
Hi,
Thanks for the feedback.
I think it is bug in the parser for this. Will have this fixed in next patch release.

~Keyang

**Comment by Keyang** [comment]
Released the fix in v 2.0.5
