### ISSUE TITLE
Skip error record and continue with rest of lines

### ISSUE THREAD

**Issue by rajashekhargundeti** [Keyang/node-csvtojson#267]
Hi,

Do we have a way to ignore erroneous line/record and continue with rest of the data.

As of now, on error, it is terminating the process and not processing the remaining valid records.

Thanks,
Raja

**Comment by Keyang** [comment]
Hi,
There are ways to skip some validation.
Could you paste some sample csv data that you got error?

~Keyang

**Comment by rajashekhargundeti** [comment]
Here is my erroneous record:
EX1234;Germany Weiss spol. s r.o.;Zebra ;XZ;126 01;Ricklal - Jazlovice;"C/O Dutch Data Distribution, s.r.o;Log. Pork CTC, Nova Kicha;CZ;32947;Thor u Tachova

delimiter is ';', when the record is encountered with single double quote(unclosed quote), it is failing and skipping the remaining..

**Comment by Keyang** [comment]
Hi,
you could turn off quote detection by setting `quote:'off'`. 
Would this fix your issue?

~Keyang

**Comment by rajashekhargundeti** [comment]
Thank you. It works.
