### ISSUE TITLE
TypeError: Cannot read property 'objectMode' of undefined | TypeError: Cannot read property 'corked' of undefined

### ISSUE THREAD

**Issue by shaharyar123** [Keyang/node-csvtojson#271]
I have been using `csvtojson/v2` with **Jest** (Nest js tests).
It was working fine till `v2.0.6 ` but when i upgrade it to `v2.0.7` it starts giving errors : 

`TypeError: Cannot read property 'objectMode' of undefined`
`TypeError: Cannot read property 'corked' of undefined`

**Comment by Keyang** [comment]
Hi,
Would you test it with `v2.0.8`?

Regards,
Keyang

**Comment by shaharyar123** [comment]
i moved down to `v2.0.6` because `v2.0.8` wasnt released at that time.

**Comment by fernando-mf** [comment]
Had this error today with the `tar-stream` module in jest. 

`TypeError: Cannot read property 'objectMode' of undefined`

Disabling `resetModules` fixed the issue

**Comment by noam7700** [comment]
+1 for @fernando-mf . had the same problem with jest with stream-related package (i think `archiver`).
