### ISSUE TITLE
await error

### ISSUE THREAD

**Issue by Crashnorun** [Keyang/node-csvtojson#272]
Hi @Keyang ,
Thanks for putting this library together. I've tried a couple of the examples you have in the documentation and I'm running into a problem when I try to use "await". Below is the sample code I'm using, which is similar to [your example](https://github.com/Keyang/node-csvtojson#from-csv-file-to-json-array)

```
const jsonArray =await csvToJson()
      .fromFile(csv)
      .then((jsonObj) => {
          console.log(jsonObj);
      });
console.log("JsonArray: " + jsonArray);
```
But I get the error seen below:

```
const jsonArray = await csvToJson()
                  ^^^^^
SyntaxError: await is only valid in async function
```
Can you help point out what I'm doing wrong?
Thanks

**Comment by michielmulders** [comment]
You have to wrap your await function with an async function.
You can't just place await 'in the wild'. 

Take a look at this gist on how to solve it: https://gist.github.com/michielmulders/8d99d80fbdc01aff5c52a3079e0ee996

**Comment by Keyang** [comment]
As @michielmulders mentioned, you need to use `await` in a `async` function.
