### ISSUE TITLE
Await error when running documentation example 

### ISSUE THREAD

**Issue by Coqueiro** [Keyang/node-csvtojson#283]
I'm trying to run the following example, [shown in documentation](https://github.com/Keyang/node-csvtojson/blob/master/docs/csvtojson-v2.md#csv-json-record_parsed-end_parsed-events-were-replaced-by-subscribe-and-then):
```js
const jsonArray=await `csv().fromString(myCSV);
```

I tried it like this:
```js
const myCSV='col0,col1,col2\n1,2,3\n4,5,6';
const jsonArray=await csv().fromString(myCSV);
console.log(jsonArray);
```

But I'm getting:
```cmd
SyntaxError: await is only valid in async function
```

Is this expected in the current version? I tried the solution given in issue https://github.com/Keyang/node-csvtojson/issues/272, but got the same problem.

I'm using version csvtojson@2.0.8, node v8.12.0.

Thanks!

**Comment by Keyang** [comment]
As #272 pointed out, `await` can only be used in an `async` function. try this:
```js
async function run(){
const myCSV='col0,col1,col2\n1,2,3\n4,5,6';
const jsonArray=await csv().fromString(myCSV);
console.log(jsonArray);
}
run();
```

**Comment by Coqueiro** [comment]
Ok, now I got it!
Is there a way to return the json object synchronously along the code? It's an interesting behaviour, when you need to return the json object to an outside function.

**Comment by Coqueiro** [comment]
Sorry, I think I solved my problem. I can return a Promise with `then` and wait for it.
Thanks for the attention!

**Comment by dchoub** [comment]
hey @Coqueiro  can you share the how you have return the promise and use the json outside the function

**Comment by punkish** [comment]
@Coqueiro @Keyang I too would like to get the result back synchronously before proceeding further in my code. Is there a documented way of doing something like the following:

```js
const jsonObj = csvSync().fromFile(csvFilePath)
const foo = jsonObj['some property']
module.exports = foo
```

**Comment by gagan-bansal** [comment]
Thanks @WORMSS using `fromString` is wise way if you want sync functionality. I was looking for same.
```js
csv().fromString(fs.readFileSync(csvFilePath, 'utf-8')); // (synchronous)
```
