### ISSUE TITLE
csvtojson conversion using danish data or other foregin letters 

### ISSUE THREAD

**Issue by testers-123** [Keyang/node-csvtojson#291]
I am trying to convert a CSV file data to JSON using csvtojson converter in nodejs. My code is as shown below. It is absolutly fine for english language. I get an output of data as shown below if I use any danish letters. I am not sure why this is happening and how to prevent it.

const convert = require("csvtojson");
const json = await convert().fromFile(data.path); // converted to json sucessfull 
await Promise.all(json.map(async(client) => {
// have to do some validation and filtering here
}))

output : 
{
     "name": "��nch ",
    "address": "K�benhavn K",
    "email": "��jeh@mailinator.com",
    "active": true,
    "created_at": "some date",
    "updated_at": "some date"
}
Expected output
{
     "name": "øælvgade ",
    "address": "København K",
    "email": "øæjeh@mailinator.com",
    "active": true,
    "created_at": "some date",
    "updated_at": "some date"
}

**Comment by Keyang** [comment]
Hi,
you need convert the data to utf8 before using the parser as the parser wont know how your charset is encoded.
You can use iconv module to convert data. 

~Keyang

**Comment by Keyang** [comment]
#173
