### ISSUE TITLE
Merge few csv rows on some condition

### ISSUE THREAD

**Issue by arepalli-praveenkumar** [Keyang/node-csvtojson#294]
I have few rows which have related information and that all rows needs to be merged into single json object 

Example CSV:
Id, name, business, location
1, praveen, electronics, india
2, rajesh, electronics, india,
3, praveen, electronics, Japan
4, praveen, motors, Japan

Condition:
 if name and business is same then merge those rows into single object 

Output:
[{
  "id" : [1, 3],
  "name" : "praveen",
  "business" : "electronics",
  "location" : ["india", "Japan"]
},{
  "id" : [4],
  "name": "praveen",
  "business": "motors",
  "location" : ["japan"]
},
{
  "id" : [2],
  "name" : "rajesh",
  "business" : "electronics",
  "location" : ["india"]
}]

Any simple steps to achieve this instead of writing large for loop to compare object.

**Comment by Keyang** [comment]
Nope. you will need to write a custom script for it in `.subscribe` function. However loop is not really needed. Instead you can use hashmap and use name/business as key.

**Comment by arepalli-praveenkumar** [comment]
I found solution to my problem. 
Thanks @Keyang
