### ISSUE TITLE
Wrong UTF-8 conversion after csv reading  

### ISSUE THREAD

**Issue by arepalli-praveenkumar** [Keyang/node-csvtojson#296]
I have csv file where i can see some Chinese characters . When i use csvtojson module to convert csv to json, output doesn't have Chinese chars instead just questions or diamond symbols(???).

My code is like `.fromFile(path, {defaultEncoding: 'utf8'})` but still same ???? marks.

Please help. Did i miss any configuration ?

**Comment by SHITianhao** [comment]
some Chinese characters are encoded in a different way such as `GBK`

**Comment by arepalli-praveenkumar** [comment]
Thank you. I fixed in different way.
