### ISSUE TITLE
Is there any way to convert property names of json data to lower case in JSON output

### ISSUE THREAD

**Issue by aniltomar10** [Keyang/node-csvtojson#297]

**Comment by Keyang** [comment]
If you know the headers just simply specify them in `headers` parameter.
If you do not know, then you can change the json object in `.subscribe` callback

**Comment by aniltomar10** [comment]
Thanks. I don't think headers property will work for my case because what I want is to do case insensitive comparison between file header names and master headers list available in database. if it is matching then JSON object property should have property as it is available in database, not what is there in file.
