### ISSUE TITLE
Possible S3 stream bug, confirmation needed

### ISSUE THREAD

**Issue by katp4** [Keyang/node-csvtojson#301]
I have the following piece of code, reading a csv file from AWS S3.

```
          let writeStream = fs.createWriteStream('test.txt');
            const readStream = s3.getObject(req).createReadStream();
            readStream.on('error', function (error) {
                console.error(`Error trying to read the stream ${error}`);
            }).on('data', function (data) {
                receivedBytes += data.length
            }).on('finish', function () {
                console.log(`Received bytes ${receivedBytes}, expected 1000001`)
            });

             await csv().fromStream(readStream).pipe(writeStream)
```

When i run this with the csv() code commented out, receivedBytes is 1000001 and works flawlessly. As soon as i attach the csv loader to the stream, i can never get 1000001. I get varying byte sizes but most commonly 974433. This messes up some post processing out with your module.

Is this intended functionality or a bug?

**Comment by Keyang** [comment]
Hi,
The parser does not affect the upper stream in any normal case.
The only possibility is the parser has met some errors in csv stream while parsing and emitted an "error" which could stop the whole stream pipe -- this is not the functionality of the parser but how node.js stream works...
Would you try to listen to `error` event from the parser and see if any errors emitted?

~Keyang

**Comment by katp4** [comment]
So I've discovered that whatever preprocessing happens before preFileLine causes the amount of bytes to be inconsistent/missing so I've had to write my own parser. Thank you though for replying.

**Comment by ajmalmsali** [comment]
@Keyang  i have similar issue,
in OS X, everything works fine,
but on centOS, i pipe directly from S3 to csvtojson (the file is about 24M), i see that about 1M records are missing, 

& when i did S3 to filesystem & to csvtojson that works,

**Comment by Keyang** [comment]
@ajmalmsali Could you please paste some code snippet that causes this issue?
