### ISSUE TITLE
toArrayString

### ISSUE THREAD

**Issue by Olmer1st** [Keyang/node-csvtojson#307]
Hi,

Could you explain why you removed the toArrayString?
We have used it a lot in our project, now we was require downgrade.

Thanks

**Comment by Keyang** [comment]
The feature was removed as it was not used much and it can be easily implemented.
Also, most json downstream (e.g. mongodb driver) expects ndjson format instead. The only difference is the brackets and comma.
Actually, you are the first person asking for this.
I can add it back in  next version.

~Keyang

**Comment by Olmer1st** [comment]
Thanks a lot, it will help us to use newest version.

**Comment by Keyang** [comment]
new parameter added in 2.0.9:
downstreamFormat: "line" | "array"
default is "line" meaning ndjson format . change to "array" to get full json array output.

**Comment by andrew-hendrix** [comment]
@Keyang bit late to the party, but thanks for returning the option back! just saved my life!
