### ISSUE TITLE
Special charaters (éèàâ’...) ?

### ISSUE THREAD

**Issue by lionel-bijaoui** [Keyang/node-csvtojson#31]
Hello !

I must convert a .csv file written in French that contain special characters.
When I do that all the special characters are replaced by "�".
What can I do ?

Thank you !

**Comment by miniil** [comment]
Can you please tell me how you do this?

**Comment by Keyang** [comment]
take a look at https://github.com/bnoordhuis/node-iconv
it has doc on how to convert the encoding.
