### ISSUE TITLE
Ignore the first row

### ISSUE THREAD

**Issue by awjdigital** [Keyang/node-csvtojson#312]
The first row of the CSV file I have isn't the header but the date the file was last updated. The 2nd row is the headers. 

How can I ignore the first row?

**Comment by Keyang** [comment]
you can use `preFileLine` hook and return empty string for lines you want to skip.
see https://github.com/Keyang/node-csvtojson#csv-file-line-hook

**Comment by silesky** [comment]
> you can use preFileLine hook and return empty string for lines you want to skip.see https://github.com/Keyang/node-csvtojson#csv-file-line-hook

This does not appear to be true... 
```
    .preFileLine((fileLine, idx) => {
      return idx < 1 ? '' : fileLine;
    })
    .fromFile(path);
```

it won't skip the line altogether -- it will just add empty an empty string.
