### ISSUE TITLE
onComplete

### ISSUE THREAD

**Issue by arunramya** [Keyang/node-csvtojson#314]
csv()
.fromFile(csvFilePath)
.subscribe((json,lineNumber)=>{
  return Promise((resolve,reject)=>{
    // process the json line in asynchronous.
  })
},onError, onComplete)

how can i definr onComplete?
Please explain it

**Comment by arunramya** [comment]
Need to know all json object processed successfully.. Please give me a solution!!

**Comment by Keyang** [comment]
you can just add a calback for oncomplete?

```js
csv()
.fromFile(csvFilePath)
.subscribe((json,lineNumber)=>{
return Promise((resolve,reject)=>{
// process the json line in asynchronous.
})
},onError, ()=>{
//on complete code here
})

```

**Comment by Keyang** [comment]
in `2.0.9` you can do
```js
await csv({needEmitAll:false}).subscribe(onNext,onError)
```
or
```js
csv({needEmitAll:false}).subscribe(onNext,onError).then(onComplete)
```

**Comment by Keyang** [comment]
developed in 2.0.9
