### ISSUE TITLE
unix file format required

### ISSUE THREAD

**Issue by VRMartin** [Keyang/node-csvtojson#315]
Love this package. Very helpful. Main issue: if the csv file is in msdos format i.e. line endings: "\r\n" instead of just "\n" the results are unpredictable.

**Comment by mayorandrew** [comment]
Have you tried setting the `eol` parameter?
```
csv({ eol: '\r\n' })
```

**Comment by VRMartin** [comment]
I was unaware of that. Thank you.

**Comment by VRMartin** [comment]
You do have to be aware of the line terminators, and you may have to specify 'eol' in the options, like csv({ eol: '\r\n' }).
