### ISSUE TITLE
ERROR: (await-promise): Invalid 'await' of a non-Promise value.

### ISSUE THREAD

**Issue by dueldanov** [Keyang/node-csvtojson#319]
csvtojson version: 2.0.8
typescript: 3.4.5
tslint: 5.16.0

I get the error in title using the documented example.
When I look at the function fromFile indeed it doesn't return promise, it returns Converter?

`fromFile(filePath: string, options?: string | CreateReadStreamOption | undefined): Converter `

Here's how I use it: 

    export const parseCsv = async (csvFile: File) => {
      const converter = csv({
        flatKeys: true,
        ignoreEmpty: true,
      })
      .on('error', (err) => {
        throw Error(err.message);
      });

      const jsonArray: CsvRow[] = await converter.fromFile(csvFile.path);
    };

**Comment by Keyang** [comment]
Hi,
It is a TSLint configure thing.
Converter implement PromiseLike interface which is Thenable.
See here: https://palantir.github.io/tslint/rules/await-promise/

~Keyang
