### ISSUE TITLE
How to trigger error if expected headers not present

### ISSUE THREAD

**Issue by dougal83** [Keyang/node-csvtojson#322]
What would be the advised route to detect headers not found as expected?  Aim is to throw an error if someone uploaded a file without defined headers.

Thanks for any advice.

**Comment by arvindkhadri** [comment]
Hi @dougal83, am also looking for a solution for the same problem. I had been using the following 

```ts
data = await csv({
      ignoreEmpty: true,
    })
      .fromString(file.buffer.toString()).preFileLine((fileLine, idx) => {
        if (idx === 0) {
          return fileLine.toLowerCase();
        }
        return fileLine;
      })
      .on("header", (header) => {
        const headers = ["barcode", "mrp", "quantity"];
        const result = headers.every((val) => header.includes(val));
        if (!result) {
          throw new UnprocessableEntityException({ message: `File has missing headers. Required headers are ${headers}` });
        }
        return header;
      })
```
I was expecting that the `throw` will stop the execution flow, but it does not. `data` has the first row of CSV and continues further with it.
