### ISSUE TITLE
cannot convert string contains "..." as a JSON key

### ISSUE THREAD

**Issue by hungchun0201** [Keyang/node-csvtojson#324]
Hi,I tried the following .csv file

a...,b
1,2

but the output was 
`[ { a: { '': [Object] }, b: '2' } ]`
which was expected to be 
`[{'a...':'1','b':'2'}]`
Please tell me how to fix it,thanks.

**Comment by Keyang** [comment]
This is a bug in parser. it is fixed in 2.0.9
