### ISSUE TITLE
Release notes or changelogs ?

### ISSUE THREAD

**Issue by popod** [Keyang/node-csvtojson#325]
Could you please add some release notes or changelogs to tell us what change between versions ? It would be very useful for us to know it in a very simple way..

Juste a "internal changes" or "fix: xxx" or "feature: xxx" in github release description or a `changelogs.md` will be enough.

Thanks in advance

**Comment by Keyang** [comment]
Thanks. 
Added release note here: https://github.com/Keyang/node-csvtojson/releases/tag/v2.0.10

**Comment by popod** [comment]
Super ! Thanks
