### ISSUE TITLE
tab delimiter?

### ISSUE THREAD

**Issue by dcsan** [Keyang/node-csvtojson#33]
how do i specify a tab delim at the cmd line?
i tried 

    csvtojson --delimiter='\t' data.tsv
    csvtojson --delimiter='¥t' data.tsv

also the | seems to get taken as a pipe in the cmd:
```
csvtojson --delimiter=| data/jgram/comments.tsv
zsh: permission denied: data/jgram/comments.tsv
```

**Comment by Keyang** [comment]
Close due to no response.

**Comment by dcsan** [comment]
thanks, your comment before helped.
