### ISSUE TITLE
Counting bug in preFileLine() when using subscribe() as well.

### ISSUE THREAD

**Issue by chaeron** [Keyang/node-csvtojson#330]
I'm doing something like this:

csv( { quote: false, nullObject: true, eol: "\r" } )
            .fromFile( path.join( dirpath, file ) )
            .preFileLine( ( line, lineIdx ) => {
                       // Some code including:
                       console.log( "File line: " + lineIdx );
            } )
           .subscribe( ( json, line ) => {
                    // Some code including:
                    console.log( "Sub line: " + line );
           }, 
                () => {},
                () => { // my completion function
                         }
            );
 );

The problem I see is that I get output like this:

File line: 0
File line: 1
File line: 2
File line: 3
....
File line: 480
File line: 481
File line: 482
**File line: 483**
Sub line: 0
Sub line: 1
Sub line: 2
Sub line: 3
....
Sub line: 480
Sub line: 481
Sub line: 482
**File line: 483**
File line: 484
File line: 485

I get two calls to preFileLine with the SAME lineIdx value!  That is not right.

Only happens once per file, regardless of file size. 

What line has the duplicate preFileLine idx value changes depending on whether I'm processing one file or multiple ones in sequence.

It's especially problematic when File line: 0 (the header line) repeats which I have seen happen, since I've been using lineIdx == 0 as an indication that I should do something with the header line before continuing!

Sounds like some kind of internal counting error.

**Comment by dogabudak** [comment]
Hey @chaeron , i know its late but i was checking the issue that you reported. After running some tests i couldn't find any inconsistencies in this issue. Can you share more details so i can maybe replicate the issue ?

**Comment by chaeron** [comment]
Due to the issues we had with csvtojson and the awkwardness of using it, we transitioned to using ExcelJS instead which also let us easily read xlsx files, not just CSVs, so this is not something that concerns us any more and not something that we can afford to invest any more time in. 

Sorry.
