### ISSUE TITLE
Ignore blank fields

### ISSUE THREAD

**Issue by AlasdairGray** [Keyang/node-csvtojson#34]
Is there a command line option to ignore fields in a record that do not have a value?
For example the following csv file
```
col1, col2, col3
d1,,d3
```
would become
```
{
  col1:"d1",
  col3:"d3"
}
```

I'm particularly interested in this feature for use with arrays
```
col1, col2[], col2[]
d1,,d3
```
would become
```
{
  col1: "d1",
  col2: ["d3"]
}
```

**Comment by djibythiaw** [comment]
Hi 
I've the same problem as yours. Do you have a solution ??

**Comment by AlasdairGray** [comment]
I have ended up using [OpenRefine](http://www.openrefine.org/) to solve my problem

**Comment by djibythiaw** [comment]
Ah oki. For me i've to do it manually in the node.js server side. Do don't you know a module who can do that ??

**Comment by djibythiaw** [comment]
Finally I will do taht manually I think it's more faster than looking for an existing solution. Thanks for your help. :-D

**Comment by Keyang** [comment]
Happy New Year.
Sorry for the late reply.
This seems a reasonable feature to be added in.
I will add this in next release.

Regards,
Keyang

**Comment by tobybellwood** [comment]
+1 from me - I'd love to see the null value removal.

Thanks for an awesome converter!!

**Comment by Keyang** [comment]
Good news. I have add this feature in v 0.3.21
Now just pass in ignoreEmpty:true in constructor which will do the trick.
Worked as both Command Line and Lib.

Regards,
Keyang

**Comment by djibythiaw** [comment]
thanks a lot for this feature. you have done a good work !!

**Comment by tobybellwood** [comment]
Great work!
