### ISSUE TITLE
Clearer Error Message for failed path

### ISSUE THREAD

**Issue by SephReed** [Keyang/node-csvtojson#356]
These lines:
https://github.com/Keyang/node-csvtojson/blob/e5ce6cf5141e26790b3499d5465a5ce775306e63/src/Converter.ts#L49-L53

Would be much more useful if the error included the `filePath` variable.

```
this.emit('error', new Error(`File does not exist at "${filePath}". Check to make sure the file path to your csv is correct.`));
```

**Comment by paddymahadeva** [comment]
> 
> 
> These lines:
> 
> https://github.com/Keyang/node-csvtojson/blob/e5ce6cf5141e26790b3499d5465a5ce775306e63/src/Converter.ts#L49-L53
> 
> Would be much more useful if the error included the `filePath` variable.
> 
> ```
> this.emit('error', new Error(`File does not exist at "${filePath}". Check to make sure the file path to your csv is correct.`));
> ```

Yep. I agree. Right now I am facing an issue with this. When I do fs.existssync() , I see the file exists. But CSVtoJSON is telling me file does not exist.. The above error message would have given more clarity.
