### ISSUE TITLE
Column Array in Multiple Lines

### ISSUE THREAD

**Issue by dgkmurthy** [Keyang/node-csvtojson#36]
Is possible to load column arrays joining data from multiple lines in case if we have 1..n number of indexes to be loaded we can not have multiple columns defined, instead it is easier to have multiple lines of data.

Example:

name, age, employer[].name, employer[].startDate, employer[].endDate
Paul, 38, Company 1, 01-01-2010, 20-08-2011
        ,    , Company 2,  21-08-2011, 21-01-2015

Thanks,
DGKM

**Comment by Keyang** [comment]
Interesting feature.
By default, it is not supported.
I believe it can be done by writing a customised parser (see https://github.com/Keyang/node-csvtojson#parser) 

Regards,
Keyang

**Comment by Keyang** [comment]
Close due to out of date.
