### ISSUE TITLE
async csvtojson appears to be blocking

### ISSUE THREAD

**Issue by jmpresso** [Keyang/node-csvtojson#363]
Platform: Tested Windows + Linux
Node: v12
csvtojson version: 2.0.10

I have a Node / Express web application. I have an async express route I am testing (though, typically it should kick off in the background as an async task). It's purpose is to retrieve some data, and parse it with csvtojson. It is a somewhat large file. On Windows on my desktop, it takes ~35 seconds to complete. However when csvtojson is processing, it temporarily hangs all other calls through Express till it completes. Basically, it appears to be behaving like a blocking synchronous call. I am not sure why, as I am using async/await. I don't know whether something is incorrect with that, or it's just using all node's memory or CPU and blocking it that way or something.

Here is my snippet in question:

```
async function convertCsv(someData) {
    
    let jsonObj = await csv({
        colParser: {
           
        },
        checkType:true
    })
     .fromString(someData);

    return jsonObj;
}
```

My upstream async should be set up appropriately. To confirm, I tested with this:

```
async function convertCsv(someData) {
   let jsonObj;
   await delay(15000);

    return jsonObj;
}

 function delay(t, val) {
    return new Promise(function(resolve) {
        setTimeout(function() {
            resolve(val);
        }, t);
    });
 }
```

With this code, while the delay was running, my webapp was still completely usable.

Any thoughts?

**Comment by hacocacyb** [comment]
If you use the fromFile or fromStream options, then it should be asynchronous non-blocking, and utilize promises to take action between reading the next record.

The fromString function is blocking and that can't be changed by putting it in an async function.

**Comment by jmpresso** [comment]
@hacocacyb Thank you for the response and assistance!

Basically my string of data comes from an axios call. I switched axios to use a stream instead. I used the exact same code with except for using fromStream with csv. It is indeed no longer blocking, and everything continues to function. There is some noticeable performance segregation though, but it's definitely better than it was before.
