### ISSUE TITLE
incorrectly get array instead of string

### ISSUE THREAD

**Issue by lzl124631x** [Keyang/node-csvtojson#371]
I'm parsing [this csv](https://github.com/shaman-lab/COVID-19Projection_0324/blob/master/bed_50contact.csv) and got `[null,null,null,null,null,"0"]` when retrieving the `hosp_need_2` field of each row.

```
csv()
  .fromFile(csvFilePath)
  .then(json => {
    console.log(JSON.stringify(json[0].hosp_need_2));
  });
// [null,null,null,null,null,"0"]
```

Note that `csv-parse` can parse this correctly. 

```
parse(fs.readFileSync("./csv/bed_50contact.csv"), { columns: true }, (err, output) => {
  console.log(output[1]);
});
```

I got 

```
{
  county: 'Baldwin County AL',
  fips: '01003',
  Date: '03/24/20',
  'hosp_need_2.5': '0',
  hosp_need_25: '0',
  hosp_need_50: '0',
  hosp_need_75: '0',
  'hosp_need_97.5': '0',
  'ICU_need_2.5': '0',
  ICU_need_25: '0',
  ICU_need_50: '0',
  ICU_need_75: '0',
  'ICU_need_97.5': '0',
  'vent_need_2.5': '0',
  vent_need_25: '0',
  vent_need_50: '0',
  vent_need_75: '0',
  'vent_need_97.5': '0',
  'death_2.5': '0',
  death_25: '0',
  death_50: '0',
  death_75: '0',
  'death_97.5': '0'
}
```

**Comment by Keyang** [comment]
Hi,
As your head row contains dot (.) e.g.  hosp_need_2.5 it will be
interpreted as nested json.
you will need set "flatKeys" option to "true"
csv({flatKeys:true}).fromFile should work fine

Regards,
Keyang

**Comment by lzl124631x** [comment]
Sorry I didn't get a chance to test it out and I ended up using `csv-parse`. I would suggest making that the default behavior so that we can by default get the same result as from `csv-parse`
