### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by jeremyrajan** [Keyang/node-csvtojson#377]
Hi @Keyang!

Thanks for the great lib! Works like a charm 😄! I see that the last publish to npm was 9 months and a few issues/PR's in the queue? Wanted to check, if this lib is maintained and/or looking for maintainers?

Cheers,
Jeremy

**Comment by nirlanka** [comment]
Agreed. This feels like a pretty cool library. Worried if it's abandoned.

**Comment by Keyang** [comment]
Hi,
Thanks a lot for your reminding. And thanks for your support of node-csvtojson library.
There were a lot of changes in my career last year and I barely had time to maintain this library.
I planed to continue supporting this library. And yes,  anyone wants to be a collaborator / maintainer are welcome! 
I will create another thread for people being interested in contributing.

Sincerely,
Keyang
