### ISSUE TITLE
Having extra comma (,) while creating array of objects through stream 

### ISSUE THREAD

**Issue by ravibadoni** [Keyang/node-csvtojson#389]
Hi all,

I am getting an issue while creating csv to json. The code I am using is->
`readStream.pipe(csv({downstreamFormat:"array"}))
                .on('header',(header)=> {
                    header.map((header) => header.toString().trim().replace(/[.]/g, ""))
                    resolve(header);
                })
                .pipe(writeStream)
                .on('finish', resolve)
                .on('error', reject);
        })`

Issue I am getting is

1) It creates csv to json but inserting extra comma at the last object, That is creating error while parsing the json file.
`[
{"id":"39"Longitude":"12121","status":"True","Country":"USA"}
{"id":"39"Longitude":"12121","status":"True","Country":"USA"},
{"id":"39"Longitude":"12121","status":"True","Country":"USA"},
]`

2) Can someone also help me with this, 
I want to get the header values only after all data parsing is done as I am gettng header values first but at the background the parsing is under progress.

Thanks in advance

**Comment by ravibadoni** [comment]
Any solution Please.

**Comment by Kugeleis** [comment]
same here - is there progress on this issue?

**Comment by ravibadoni** [comment]
> same here - is there progress on this issue?

https://github.com/Keyang/node-csvtojson/issues/333

Yes. Please have a look at this ticket
