### ISSUE TITLE
Conversion chokes on single quotation

### ISSUE THREAD

**Issue by dbpc** [Keyang/node-csvtojson#39]
I receive the error "Incomplete CSV file detected. Quotes does not match in pairs." on a tab-delimited file, where this entry includes a " to indicate inches. 

Is there a way to escape it or otherwise convince it to continue past it?

**Comment by Keyang** [comment]
Hi,
This issue was addressed in version 0.3.18.
You could use two double quotes to represent a double quote as per CSV standard.
e.g.
3""15 will be converted to 3"15

Regards,
Keyang

**Comment by dbpc** [comment]
Unfortunately I have no control over the incoming CSV, it's a third-party company managing an inventory and spitting it out to our machine (and they're impossible to get a hold of.) I'd love to do all the work in Node instead of getting Powershell involved to scrub the CSV.

**Comment by Keyang** [comment]
Hmm. Can you try to change the param for quote to something else? currently it is using double quote ("). If your csv data do not need use quote then you can change to something else. See https://github.com/Keyang/node-csvtojson#params
