### ISSUE TITLE
First time using your library, example did not work for me

### ISSUE THREAD

**Issue by doverradio** [Keyang/node-csvtojson#392]
Hello, I am trying to use your library but so far I didn't get the data from my test csv file and need help.
Below is my current code, for a single component that uses your library as a button, which, when clicked, supposed to trigger the use of csvtojson.

```
const csv = require('csvtojson');
const csvFilePath = '../test.csv';
import React, { Component } from 'react'
import { Button } from 'reactstrap';
// import fs from 'fs';

const getCsv = () => {
        csv()
        .fromFile(csvFilePath)
        .then((jsonObj)=>{
            console.log(jsonObj);
            return jsonObj
        
        })
    }
    
class Csvjson extends Component {


    
    render() {
      return (
        <Button onClick={getCsv}>Get CSV</Button>

      )
    }
  }


export default Csvjson
```

It is giving errors:
`Error: Cannot find module 'fs'`

But it's not clear how this occurred when I am not calling fs.  So I left fs there commented but even when I uncomment it, it still gives same  error.

**Comment by flymans** [comment]
fs module is supported by nodejs, not raw JS
