### ISSUE TITLE
Stream does not return JSON array

### ISSUE THREAD

**Issue by yannickl** [Keyang/node-csvtojson#40]
Hi, first of all thank you for the great lib.

I have an issue to parse a CSV using the streaming API because it does not return a JSON array. I don't know if it is the "normal" behavior but here an example to explain my problem (with Node v0.12):

The original CSV file:
```csv
annee;jour;date;b_1;b_2;devise;
2015029;LUNDI   ;09/03/2015;35;31;eur;
2015028;SAMEDI  ;07/03/2015;48;9;eur;
```

The code to parse the CSV:

```js
var rs = require('fs').createReadStream('source.csv');
var ws = require('fs').createWriteStream('destination.json');

 rs.pipe(new Converter({ constuctResult: false, delimiter: ';', trim: true })).pipe(ws);
```

 The result file content:
```text
{"annee":2015029,"jour":"LUNDI","date":"09/03/2015","b_1":35,"b_2":31,"devise":"eur","":""}
{"annee":2015028,"jour":"SAMEDI","date":"07/03/2015","b_1":48,"b_2":9,"devise":"eur","":""}
```

I would expected to have this json object:
```json
[
  {"annee":2015029,"jour":"LUNDI","date":"09/03/2015","b_1":35,"b_2":31,"devise":"eur","":""},
  {"annee":2015028,"jour":"SAMEDI","date":"07/03/2015","b_1":48,"b_2":9,"devise":"eur","":""}
]
```

It works fine if I use the `end_parsed` event instead, but not with the stream and the `pipe` API.

Thank you for your help

*Note: I don't know why by it adds me an empty field in the JSON result too*

**Comment by Keyang** [comment]
Hi,
Thanks for the feedback.
I think the two problems above you have are normal behaviour of the tool.
1. csvtojsonn converts rows of csv to JSON objects( not array of JSON). each time a JSON object is ready, it will emit it. The square parentless (or line break or comma) are not part of it. However, you can easily work around it. I will add a parameter to make this working simply.
2. according to csv standard, the last element should not end with the delimiter. I believe that is the reason you have an empty element at the end. It should be like

A,B,C,D
1,2,3,4
Rather than 
A,B,C,D,
1,2,3,4,

~Keyang

**Comment by yannickl** [comment]
Thank you for your rapid feedback.

1. Ah ok, I thought it was an unexpected behavior. I'm new to the node.js (and javascript) world so I have to learn the use of streams more deeply. :)
2.  Ah yes, I didn't noticed for the last delimiter. I don't generate the csv, I just consume it from a remote endpoint.

Thank you again for your help. I close the issue and I'll follow for the change of the stream use (if it'll have).

**Comment by Keyang** [comment]
Hi,
I just released ver 0.3.19 which includes the toArrayString feature.
Try
```
 rs.pipe(new Converter({ constructResult: false, delimiter: ';', trim: true,toArrayString:true })).pipe(ws);
```
This should do what you expect.

Regards,
Keyang

**Comment by Keyang** [comment]
See details here
https://github.com/Keyang/node-csvtojson#params
The new parameter is toArrayString

~Keyang

**Comment by yannickl** [comment]
Great, I'll test it tomorrow! :+1:

**Comment by yannickl** [comment]
It works perfectly, thank you very much for your reactivity!
