### ISSUE TITLE
File encoding option

### ISSUE THREAD

**Issue by jcuenod** [Keyang/node-csvtojson#402]
I'm using `csvtojson().fromFile()`. Is it possible to add an option like `{ encoding: 'latin1' }`?

**Comment by jfoclpf** [comment]
You have to use the stream reader and change the encode type. 
```js
const fs = require('fs')
const csv = require('csvtojson')

csv()
  .fromStream(fs.createReadStream('/path/to/file', { encoding: 'latin1' }))
  .subscribe((json) => {
    console.log(json)
  },
  (err) => {
    throw err
  },
  () => {
    console.log('success')
  })
```

Chose from the encoding from this [list](https://stackoverflow.com/questions/14551608/list-of-encodings-that-node-js-supports)

**Comment by jfoclpf** [comment]
@jcuenod please close the issue if this solves your question

**Comment by jcuenod** [comment]
Sorry, I assumed leaving it open would basically be a feature request but if you'd rather have it closed, that's fine. I've long since moved on in my use case.

**Comment by jfoclpf** [comment]
Maybe you're right, it may be a useful add-on
