### ISSUE TITLE
CLI checkType usage

### ISSUE THREAD

**Issue by SkydiverFL** [Keyang/node-csvtojson#41]
What is the syntax for disabling the checkType logic via the command line?  I have a large file to convert, with a large String field, however random lines are being detected as numeric.  This is throwing off the import logic in the next app I'm using.  My goal is to have all fields treated as strings so I may convert them in the next phase of my processing.

**Comment by Keyang** [comment]
Sorry for the late response. 
Yeah it can do as all parameters can be passed through command line using following syntax 
```
--paramName=val
```
however there seems a bug for checkType as it is a boolean value. But following command line worked for me:
```
csvtojson parse --checkType= ./dataWithType
```
I will fix the issue and update the doc soon.


~Keyang

**Comment by Keyang** [comment]
Hi,
I've updated the command line to latest version in v 0.3.20
Please give a try.

~Keyang

**Comment by Keyang** [comment]
Close due to no response.
