### ISSUE TITLE
Unknown boolean value  for parameter --ignoreEmpty.

### ISSUE THREAD

**Issue by dcsan** [Keyang/node-csvtojson#42]
csvtojson --ignoreEmpty true packages/slabs/data/tiledata.csv
    Unknown boolean value  for parameter --ignoreEmpty.

I tried 1, 0, nothing and true / false.
what arguments does it expect?

**Comment by dcsan** [comment]
aha, = sign!

csvtojson --ignoreEmpty=true packages/slabs/data/tiledata.csv

**Comment by Keyang** [comment]
yeah, you need the "=".
Close the issue now.
~Keyang
