### ISSUE TITLE
Csv array is converted to single string instead of array of strings

### ISSUE THREAD

**Issue by kkorus** [Keyang/node-csvtojson#426]
Hi, here is my CSV

```csv
"name", "tags"
"test name", "[""tag1"",""tag2""]"
```
it's being converted to: 
```
{
  "name": "test name",
  "tags": "[\"tag1\",\"tag2\"]",

}
```
I would expect to get
```
"tags": ["tag1", "tag2"]
```

**Comment by dogabudak** [comment]
I would consider  "[\"tag1\",\"tag2\"]" as the expected behaviour. JSON.parse() should fix your issue.

**Comment by kkorus** [comment]
Ok, I will try to add a custom column parser.
