### ISSUE TITLE
Failure to read large csv

### ISSUE THREAD

**Issue by shailendra735** [Keyang/node-csvtojson#43]
This is my code to read the csv:
```
   var csvtojson = require("csvtojson").core.Converter,
   var fileStream = fs.createReadStream("my.csv");
    var csvConverter = new csvtojson({
      constructResult: true
    });
    fileStream.pipe(csvConverter);
    csvConverter.on("end_parsed", function(data) {
      next(null, data); //1
    });
```

The only problem I have here is that this works great for a small csv, but it fails to give any output for large csv . The `data` I receive in the `1` is an empty array.

You can get the sample csv [here] (https://docs.google.com/spreadsheets/d/1kg2ABisAUzzIk51G5VGuonDHf8w2JIxFo31JDsLdIAA/pubhtml).
It's very common for me to parse very large csv to the tune of upto 20k or even 40k records.

**Comment by Keyang** [comment]
Hi,
I believe the parser is able to handle that amount of records. I have been testing with over 300K lines of records. 
The link you put there is a link to HTML not a csv file which I cannot really test. If you can send me a link to csv file that would be good.

also construct the result will consume lot of memory. better to use stream which piping down the json objects.

~Keyang

**Comment by shailendra735** [comment]
Sorry for not providing a direct link to the csv, but I guess you can download the sheet as a csv.

**Comment by Keyang** [comment]
no i cannot download it as a csv. there is no button on that web page allowing me to download it as a csv file. and the whole page is in html format and the data is in a table element.

~Keyang

**Comment by shailendra735** [comment]
I have run into some kind of trouble here. I have a bunch of files with me and all of them are .csv. But this problem occurs in only a particular type of csvs, which have been generated by using the [node-csv](http://csv.adaltas.com/) lib. I guess there's some issue with the type of encoding. I'll research further and keep you posted. 
Thanks.

**Comment by Keyang** [comment]
Close due to not active.
