### ISSUE TITLE
Parsing Large CSV file (90k) records

### ISSUE THREAD

**Issue by blazerguns** [Keyang/node-csvtojson#44]
I have seen examples where I saw that {constructResult:false} will help reduce memory consumption. While I understand that, I have 16GB of ram and I can effort to put the result in memory and do some processing. My main issue is that it took 24 minutes to finish this work. While I understand the load, 24 minutes sounds really high!!! Can this take advantage of multi cpu cores for faster processing?

**Comment by Keyang** [comment]
Hi,
Node.JS APP is running on single thread which means App Process will only have one user thread at a time. 
Also Node.JS is not suitable for computing intensive tasks. This is the feature of Node.JS.
{constructResult:false} only avoid using much memory, it actually does not affect performance. 
My suggestion is to divide your csv file into multiple files and run csvtojson parser against them in parallel (like child_process). This will use multiple-core of your CPU. and you can concat the result after its finished.

~Keyang

**Comment by t3dodson** [comment]
This could be an interesting feature. Perhaps a --parallel=true flag. Which defaults by spawning sub processes to do the work in parallel. We should keep this on the road map in the future.

**Comment by Keyang** [comment]
Sounds like a interesting feature. The argument I think would be like --worker=<Number> which user could specify number of workers according to their CPU. This feature should be available for both CLI and Lib.

**Comment by galkatzburg** [comment]
+1

**Comment by Keyang** [comment]
Added this feature in prerealse-0.4.0 branch.
https://github.com/Keyang/node-csvtojson/tree/prerelease-0.4.0

**Comment by nmors** [comment]
+10000

**Comment by Keyang** [comment]
this feature added in 0.4.0
