### ISSUE TITLE
row and col change to read

### ISSUE THREAD

**Issue by alicera** [Keyang/node-csvtojson#441]
/*csv data
name, Joe
birthday, 1970-01-01

I want to change row and col.
Are there code example to process it ?

**Comment by jfoclpf** [comment]
What do you mean by chance row and col? Do you mean amend the title? Do you mean swap columns?

Please be more specific

**Comment by alicera** [comment]
change
```
/*csv data
name, birthday
Joe, 1970-01-01
```
to 

```
/*csv data
name, Joe
birthday, 1970-01-01
```

**Comment by jfoclpf** [comment]
This lib follows strictly CSV standard [RFC4180](https://www.loc.gov/preservation/digital/formats/fdd/fdd000323.shtml). What you're requesting is not CSV standard

> An optional header line may appear as the **first line of the file** with the same format as normal record lines. This header will contain names corresponding to the fields in the file and should contain the same number of fields as the records in the rest of the file. CSV commonly employs US-ASCII as character set, but other character sets are permitted.

You want the header to be the first column. You cannot then use any stream reader as you need to fetch the whole file before processing it to get full header, which is very inefficient for big files.
