### ISSUE TITLE
option: fork new process

### ISSUE THREAD

**Issue by Keyang** [Keyang/node-csvtojson#49]
Converting csv to json needs computing resource. it is good to have an option to allow the whole converting happen in another process so that it wont affect main process which always has busy.

**Comment by nmors** [comment]
Is anybody working on this?

**Comment by Keyang** [comment]
Yes. I am working on this and this feature will be coming with version 0.4.0

~Keyang

**Comment by Keyang** [comment]
This feature added in 0.4.0
