### ISSUE TITLE
Column filter

### ISSUE THREAD

**Issue by hodiapa** [Keyang/node-csvtojson#50]
How to filter only a desired set of columns during CSV to JSON conversion.
So I have columnA, columnB, ColumnC. 
And I would like to display only ColumncC in the JSON file.

How to go about it.

Raising an issue as I didn't find any mailing list. Thanks~

**Comment by Keyang** [comment]
use *omit* parser to exclude the column you do not want.
see here : https://github.com/Keyang/node-csvtojson#default-parsers
so in your CSV header you will have 
*omit*columnA, *omit*columnB, ColumnC
Does this solve your problem?

~Keyang

**Comment by hodiapa** [comment]
Is there a way to do this using the csvtojson api rather than manually changing the header row? If not this could be a very good feature enhancement to have to the library

**Comment by Keyang** [comment]
True. I will add this in road map.
Thanks for the suggestion.

~Keyang
