### ISSUE TITLE
avoid dot(.) in headers as nested JSON?

### ISSUE THREAD

**Issue by gv-rayalab** [Keyang/node-csvtojson#51]
Hi  how i can use the default parser but avoid the representation of dot(.) in a header as a nested JSON? or the only options is to create a custom parser?

Thanks

**Comment by Keyang** [comment]
Good point.. It will be a new feature. Thanks.

~Keyang

**Comment by atufkas** [comment]
:+1:

**Comment by Keyang** [comment]
Added
* --flatKeys 
* flat parser
