### ISSUE TITLE
constructResult true or false

### ISSUE THREAD

**Issue by gepser** [Keyang/node-csvtojson#56]
(This is a question so, please label it as that)

Hi, let me thank you for this repo, it is great!

I am using it a lot and I was wondering if I am managing large files using `{constructResult:false}` and then I need to upload the entire `json` to memory right after the `json` file is complete, it would be the same if I use `{constructResult:true}` and having the `json` directly in memory? Does that make any sense?

Thanks!

**Comment by Keyang** [comment]
To avoid memory consuming of big data, Node.JS uses Stream which allows large data being processed and transferred without loading them completely into memory. 

csvtojson module completely supports Stream. You can use standard Stream APIs (see https://nodejs.org/api/stream.html) to transfer converted JSON data to any writable stream (like web request, file writer, and others)

simply example:
```js
var convert=new require("csvtojson").Converter({constructResult:false});
var rs=require("fs").createReadStream("mycsv.csv");
var ws=require("request").post("http://mywebsite.com/upload");
rs.pipe(convert).pipe(ws);
```

in the example above, it will not load whole csv file or converted json data into memory.

**Comment by gepser** [comment]
Thanks @Keyang, I have a clearer idea now.
