### ISSUE TITLE
Error handle Options needed

### ISSUE THREAD

**Issue by xianlin** [Keyang/node-csvtojson#57]
Hi Keyang

The current csvtojson does not support invalid CSV file conversion error handle. (See http://stackoverflow.com/questions/30028453/how-to-handle-incomplete-csv-file-detected-quotes-does-not-match-in-pairs)

Is it possible to let csvtojson **emit** invalid csv (e.g. a binary file with fake.csv name) when it detects the error.

Currently nodejs will report "Incomplete CSV file detected. Quotes does not match in pairs" message. It would be nice to emit "invalid csv" message at this error so we can catch the error and handle it.

I know we should have our separate CSV validation code but most of other CSV nodejs module already have validation and conversion built in. I really want to use your module as it provides convenience as in convert csv to json but it could be better by including this "emit invalid csv file message" feature instead of just print out a message to the console.

Thanks.

**Comment by Keyang** [comment]
I will include this in next version.
Thanks.

**Comment by jsgandalf** [comment]
+1 to this, thanks!

**Comment by Keyang** [comment]
Added error handling since v0.4.4
