### ISSUE TITLE
Can I omit a specific column before the conversion

### ISSUE THREAD

**Issue by KhaledMohamedP** [Keyang/node-csvtojson#60]
Is it possible, in the current state of this module, to omit a specific column form CSV before getting the JSON result. 

e.g 
``` csv
id, name, age, address
 1, john,  25, 120 road ave
```
I want to omit address before converting the data to JSON.

**Comment by Keyang** [comment]
Yes. You can use default parser:omit to omit a specific  column. See here
https://github.com/Keyang/node-csvtojson/blob/master/readme.md#default-parsers

Keyang

**Comment by KhaledMohamedP** [comment]
I missed this from the doc 
`"*omit*address"`
👍

**Comment by KhaledMohamedP** [comment]
@Keyang  what if I don't want to miss with the original data, can I set my own header  where i can omit the column needed.

**Comment by Keyang** [comment]
Yes. Subscribe to record_parsed event. Change the result object directly
there for each line of csv row.

csvConverter.on("record_parsed",function(resultRow,rawRow,rowIndex){
   console.log(resultRow); //here is your result json object
});


Or you can write your own parser.

Keyang

**Comment by KhaledMohamedP** [comment]
great thanks :+1:
