### ISSUE TITLE
Process out of memory error with example code

### ISSUE THREAD

**Issue by BurntPancake** [Keyang/node-csvtojson#62]
Hi,

I am trying to process a 4G cvs file while doing customised parsing and I've encountered process out of memory error.

I tried to identify the problem - I then found out that even with the example code I still get out of memory error. However, ```csvtojson [path to bigcsvdata] > converted.son``` works fine.

The example code mentioned above are:
```
var Converter=require("csvtojson").Converter;
var csvConverter=new Converter({constructResult:false}); // The parameter false will turn off final result construction. It can avoid huge memory consumption while parsing. The trade off is final result will not be populated to end_parsed event.

var readStream=require("fs").createReadStream("inputData.csv");

var writeStream=require("fs").createWriteStream("outpuData.json");

readStream.pipe(csvConverter).pipe(writeStream);
```

The error happened in Result._write:30:25

**Comment by Keyang** [comment]
Hi,
I cannot re-produce the issue you have.
What is the version you are using and what's the operation system?
We have been using the module to process csv files bigger than 8.5GB under
linux and MacOs without the issue.

Also if {constructResult:false} being set, it should not get to line
Result._write:30
where the result is being buffered in memory.

Regards,
Keyang

**Comment by BurntPancake** [comment]
I ended up using the cvs module, which unfortunately doesn't convert to json automatically.

I just tested it again and the test code mentioned above worked now. Sorry for the confusion. 

However, could you please tell me why I'm getting invalid string length error at Result._write in my code with customised parser?
I was using the latest 0.4.4 and I tried to run it on both MacOS and Ubuntu. On Ubuntu it's out of memory, on my mac it's invalid string length(which is essentially out of memory as well).

The code I used was

```javascript
var Converter = require("csvtojson").Converter;
var converter = new Converter({headers:["Med", "PT", "DT", "NP", "Dis", "Path"], constrcutResult:false, checkType:true});

var parserMgr=require("csvtojson").parserMgr;

//parse latlngList field data format to {Path : [{lat : 123, lng: 456}, ..., ...]}

parserMgr.addParser("myParserName",/Path/,function (params){
    var coorArray = params.item.split(',');
    var coorPair = {lat : 0, lng : 0};
    var coorPairArray = [];
    for(var i = 1; i < coorArray.length+1; i++)
    {
        if(i%2 === 1)
        {
            coorPair.lat = coorArray[i-1];
        }
        else
        {
            coorPair.lng = coorArray[i-1];
            coorPairArray.push(coorPair);
            coorPair = {lat : 0, lng : 0};
        }

    }
    params.resultRow['Path']=JSON.stringify(coorPairArray);
});

//end_parsed will be emitted once parsing finished
//Note: Only used when dealing with small csv files
/*
converter.on("end_parsed", function (jsonArray) {
    //console.log(jsonArray);
    console.log("Parse finished");
});
*/
//read from file
var readStream = require("fs").createReadStream(fileName);
var writeStream=require("fs").createWriteStream(outputName);
readStream.pipe(converter).pipe(writeStream);
```

**Comment by BurntPancake** [comment]
Hi,

I found out where was wrong. I misspelled constructResult. This is very embarrassing. Please close this issue.

Thank you very much and sorry for the trouble! I would not have thought of it if I haven't seen your second paragraph.

**Comment by Keyang** [comment]
No problem. Thanks for your cooperating.

~Keyang
