### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by diegoaguilar** [Keyang/node-csvtojson#67]
I noticed a [file's first line got something wrong  when parsing](https://gist.github.com/diegoaguilar/4a67a3757220495bc938), CSV file has got not headers at first line.

Previoulsy I was trying:

    var successEHSInjectedHeader = 'First Name,Last Name,Home Phone,Appointment Date, Appointment Time,Patient ID,Scheduling Resource ID,Office Location ID,Office Location Name,Physician Full Name,Patient Street Address,Patient City,Patient State,Patient Zip,Patient Other Phone,Patient Date of Birth,Appointment Type';
    var csvConverter = new Converter({
        constructResult: true
    });
    file.buffer = successEHSInjectedHeader + '\n' + file.buffer;
    csvConverter.fromString(file.buffer, function(err, json) {
        ....
    });

Which gives following output:

```json
[ { 'Appointment Type\nPACO': 'GDX', 'Patient Date of Birth': '04/10/1966', 'Patient Other Phone': 504, 'Patient Zip': 70058, 'Patient State': 'LW', 'Patient City': 'HWLVWY', 'Patient Street Address': '1140 TWNEWE DL WPT W', 'Physician Full Name': 'EWLVMCWE XPTXMWTLY', 'Office Location Name': 'ET THXMWE CHC WT MWHWLMW', 'Office Location ID': 102, 'Scheduling Resource ID': 16, 'Patient ID': 65779, 'Appointment Time': '10:00', 'Appointment Date': '09/12/16', 'Home Phone': 4152219931, 'Last Name': 'GWLLMEXN', 'First Name': 'LMEW' }, { 'Appointment Type\nPACO': 'VFMWLD', 'Patient Date of Birth': '04/10/1966', 'Patient Other Phone': 504, 'Patient Zip': 70058, 'Patient State': 'LW', 'Patient City': 'HWLVWY', 'Patient Street Address': '1140 TWNEWE DL WPT W', 'Physician Full Name': 'EWLVMCWE XPTXMWTLY', 'Office Location Name': 'ET THXMWE CHC WT MWHWLMW', 'Office Location ID': 102, 'Scheduling Resource ID': 16, 'Patient ID': 65779, 'Appointment Time': '10:00', 'Appointment Date': '12/09/16', 'Home Phone': 4152219931, 'Last Name': 'GWLLMEXN', 'First Name': 'LMEW' } ]
```

Then I adapted code to:

    var csvConverter = new Converter({
        constructResult: true,
        noheaders: true,
    	headers: successEHSInjectedHeader
    });

Skipped the `headers  + \n` concatenation and tried the same `fromString` function (even that I HAD to use `buffer.toString` otherwise json output is `undefined`) but it's skipping first:

```javascript
[ { '55': 16,
    '102': 102,
    '65705': 65779,
    '70119': 70058,
    '4152415192': 4152219931,
    PACO: 'LMEW',
    HWNLY: 'GWLLMEXN',
    '09/10/16': '09/12/16',
    '09:00': '10:00',
    'ET THXMWE CHC WT MWHWLWW': 'ET THXMWE CHC WT MWHWLMW',
    'DXNWLD CXETWLLX': 'EWLVMCWE XPTXMWTLY',
    '1450 MWLWME ET': '1140 TWNEWE  DL WPT W',
    'SAN FRANCISCO': 'HWLVWY',
    LW: 'LW',
    '5045251551': 504,
    '08/31/1959': '04/10/1966',
    WETP_C: 'GDX' },
  { '55': 16,
    '102': 102,
    '65705': 65779,
    '70119': 70058,
    '4152415192': 4152219931,
    PACO: 'LMEW',
    HWNLY: 'GWLLMEXN',
    '09/10/16': '12/09/16',
    '09:00': '10:00',
    'ET THXMWE CHC WT MWHWLWW': 'ET THXMWE CHC WT MWHWLMW',
    'DXNWLD CXETWLLX': 'EWLVMCWE XPTXMWTLY',
    '1450 MWLWME ET': '1140 TWNEWE  DL WPT W',
    'SAN FRANCISCO': 'HWLVWY',
    LW: 'LW',
    '5045251551': 504,
    '08/31/1959': '04/10/1966',
    WETP_C: 'VFMWLD' } ]
```

I'm using last version 0.4.5. How should I fix this?

**Comment by Keyang** [comment]
Hi,
I spotted two issued in your code pasted:

1.  it is "noheader" not "noheaders" which indicates there is no header in your data.
2. the "headers" param takes an array not a string. 

So param should be like:

```json
{
    noheader:true
    headers:["fieldNameA", "fieldNameB", "fieldNameC" ]
}
```
Let me know if you still have problem after fixing the two issues.

~Keyang

**Comment by diegoaguilar** [comment]
Thanks, that solved the issues. One last question, should I pass `file.buffer` or `file.buffer.toString()`?

**Comment by Keyang** [comment]
fromString will take a string not a buffer. So you need call
toString("utf8") to convert it.
Basically, if you load data from a file, you should better use
fs.createReadStream instead of reading everything to memory..

~Keyang
