### ISSUE TITLE
Detection of an empty row in csv file

### ISSUE THREAD

**Issue by RoobiniM** [Keyang/node-csvtojson#68]
Hi,

Is there any parameter to check if a row is empty in csv file?
I have a requirement to skip the empty rows in big CSV file.
Thanks!!

**Comment by Keyang** [comment]
Hi,
Could you be more specific?
Why you need check empty row?
What is your expected behaviour for empty rows?

~Keyang

**Comment by RoobiniM** [comment]
Hi, Keyang,

Thanks for replying.
Consider that my csv file contains data as below

Name,age,Company
John,25,xxx
Dhivya,27,yyy

Samantha,28,zzz


Here the third row is empty. My requirement is to convert this csv to json by skipping the empty rows(in this case 3rd row).

**Comment by Keyang** [comment]
Hi,
If the empty row is really empty, the parser should skip it automatically.
Unless the row contains spaces.

Regards,
Keyang

**Comment by RoobiniM** [comment]
Hi Keyang,
The example that I mentioned above is actually from csv file.
When the data is read from csv file using readStream/readFileSync, it is converted into comma seperated values.
So the above data is converted into
John,25,xxx
Dhivya,27,yyy
,,
Samantha,28,zzz

Screenshot of my csv file:
![capture](https://cloud.githubusercontent.com/assets/11403107/11662154/50d1a81e-9dfb-11e5-876f-f318512c518a.JPG)

Output JSON:
[{
	"Name": "John",
	"Age": 25,
	"Company": "xxx"
}, {
	"Name": "Dhivya",
	"Age": 27,
	"Company": "yyy"
}, {
	"Name": "",
	"Age": "",
	"Company": ""
}, {
	"Name": "Samantha",
	"Age": 28,
	"Company": "zzz"
}]

Thanks,
M.Roobini

**Comment by Keyang** [comment]
Hi,
Thanks for the feedback.
There was a parameter "ignoreEmpty". It needs to be true to ignore empty columns.
However there is a bug when all columns are empty.
I have patched the issue in version 0.4.7
Please give a try and let me know.

~Keyang

**Comment by RoobiniM** [comment]
Hi Keyang,
Thanks for fixing it.
However, all the valid rows after the empty row are getting deleted now.

Input CSV:
![capture](https://cloud.githubusercontent.com/assets/11403107/11762140/a1785b9a-a103-11e5-859b-78fdfc8d147b.JPG)

Output JSON:
[{"Name":"John","Age":25,"Company":"xxx"},{"Name":"Dhivya","Age":27,"Company":"yyy"}]

Here, the third row is empty and the fourth row contains valid data but the output json contains only the first two rows.

Thanks,
M.Roobini

**Comment by Keyang** [comment]
That's a good find.
I have patched this in version 0.4.8
Thanks

Keyang
