### ISSUE TITLE
Elimination of Extra columns in CSV When noheader is true.

### ISSUE THREAD

**Issue by RoobiniM** [Keyang/node-csvtojson#69]
Hi Keyang,
Consider my csv file contains the below data.

InputCSV:

John,25,XXX
Samantha,28,YYY,7

while converting this file to json with noheader as true, the fourth column is getting eliminated.

OutputJSON:

[ { field1: 'John', field2: '25', field3: 'XXX' },
  { field1: 'Samantha', field2: '28', field3: 'YYY' } ]

Issue: Missing field4 in the 2nd row.

Thanks,
M.Roobini

**Comment by lgodard** [comment]
Hi,
I experience a similar problem, but not sure it is the same (moreover, seems a regression)

inputCSV (tabulated \t)
head1 \t head2 \t head3  \t head4 \t head5
John \t \t 25 \t XXX \t
Sam\t \t 28 \t YYY \t

note empty data in column2 and column 5

output
[{head1;'John', head2: '', head3: '25', head4: 'XXX'},
{head1;'Sam', head2: '', head3: '28', head4: 'YYY'}]

column2 is OK
issue : head5 is not taken into account

this seems a regression as it works using version 0.4.5  (head5 is correctly set)

thanks a lot

Laurent

**Comment by RoobiniM** [comment]
Hi Laurent,

Thanks for replying, but this issue is different. My CSV does not contain header fields. If the first row contains 3 columns, only the first three columns of all rows are getting converted to json irrespective of the number of columns present in other rows. (e.g. if 2nd row contains 4 columns, the fourth column is ignored.)

InputCSV:

John,25,XXX
Samantha,28,YYY,7

Note: The first row should not contain the delimiter "," at the end.

Thanks,
M.Roobini

**Comment by lgodard** [comment]
Hi
sorry then for the hijack :-/
i'll open a new issue
Laurent

**Comment by Keyang** [comment]
This is a bug with noheader parameter.
Will look into this.

Thanks,
Keyang

**Comment by Keyang** [comment]
I patched the issue in version 0.5.0
please give a try .

Regards,
Keyang

**Comment by RoobiniM** [comment]
Thanks a lot!!!
The issue is resolved.

Regards,
M.Roobini
