### ISSUE TITLE
The last column is not defined if empty despite header

### ISSUE THREAD

**Issue by lgodard** [Keyang/node-csvtojson#70]
Hi,
I experience a regression since 0.4.5 version 
If the last data of line is empty, the json does not take care of it instead of setting it to ''

inputCSV (tabulated \t)
head1 \t head2 \t head3 \t head4 \t head5
John \t \t 25 \t XXX \t
Sam\t \t 28 \t YYY \t

note empty data in column2 and column 5

output
[{head1;'John', head2: '', head3: '25', head4: 'XXX'},
{head1;'Sam', head2: '', head3: '28', head4: 'YYY'}]

column2 is OK
issue : head5 is not taken into account

This worked perfectly in version 0.4.5 as head5 was set as expected (head5: '')

thanks a lot

Laurent

**Comment by Keyang** [comment]
Hi,
Could you let me know what version you have problem with?
I am using 0.4.8 which seems have no this issue.
see output below:

```
[
{"head1":"John","head2":"","head3":25,"head4":"XXX","head5":""},
{"head1":"Sam","head2":"","head3":28,"head4":"YYY","head5":""}
]
```

~Keyang

**Comment by lgodard** [comment]
Hi

Thanks a lot for your response

So, I just tested the versions 0.4.5 , 0.4.6, 0.4.7 --> all is correct
Testing the 0.4.8 is NOT ok, lack the last field

feel free to ask if more needed and thanks again

Laurent

here are the ouputs

* version 0.4.7

{ JournalCode: 'XX',
  JournalLib: 'XX',
  EcritureNum: Y,
  EcritureDate: YYYY,
  CompteNum: YYYY,
  CompteLib: 'ZZZZZZ',
  CompAuxNum: '',
  CompAuxLib: '',
  PieceRef: 'AAAAA',
  PieceDate: BBBB,
  EcritureLib: 'CCCCC',
  Debit: 'DDDD',
  Credit: 'EEEE',
  EcritureLet: '',
  DateLet: '',
  ValidDate: FFFFF,
  Montantdevise: 'GGGGG',
  Idevise: '' }

* version 0.4.8 ( lacks the last field Idevise: '' )

{ JournalCode: 'XX',
  JournalLib: 'XX',
  EcritureNum: Y,
  EcritureDate: YYYY,
  CompteNum: YYYY,
  CompteLib: 'ZZZZZZ',
  CompAuxNum: '',
  CompAuxLib: '',
  PieceRef: 'AAAAA',
  PieceDate: BBBB,
  EcritureLib: 'CCCCC',
  Debit: 'DDDD',
  Credit: 'EEEE',
  EcritureLet: '',
  DateLet: '',
  ValidDate: FFFFF,
  Montantdevise: 'GGGGG' }

**Comment by Keyang** [comment]
That's interesting.
Could you please upload the csv file to somewhere like http://fileota.com ?

Regards,
Keyang

**Comment by lgodard** [comment]
HI, here is joined a small csv example that experience the problem

[111111111FEC20150630.txt](https://github.com/Keyang/node-csvtojson/files/65510/111111111FEC20150630.txt)

BUT
tested on 0.4.5 and 0.4.6 --> OK
tested on 0.4.7 and 0.4.8 --> PROBLEM

same problem, Idevise: ''  is missing

really strange that the test is not consistent with my big file, but the problem still there

Thanks a lot Keyang

Laurent

**Comment by Keyang** [comment]
That's perfect.
I can see the issue now.
Will take a look soon.

~Keyang

**Comment by Keyang** [comment]
Hi,
I patched the issue in version 0.5.0
could you please try if it is ok for you?

~Keyang

**Comment by lgodard** [comment]
Hi,
Just tested and it works like a charm
Problem solved for me
moreover, seems that speed is improved
That's a great and wonderful job
Thanks a lot
Laurent

**Comment by lgodard** [comment]
closing the issue
