### ISSUE TITLE
CSV Parsing is improper when the csv file is saved as CSV (Macintosh) (*.csv)

### ISSUE THREAD

**Issue by RoobiniM** [Keyang/node-csvtojson#71]
Hi Keyang,
When csv file is saved as CSV (MAC) format, each line is separated by the delimiter "\r", hence csv parsing is getting failed.

Input CSV ( saved in CSV (MAC) format):
John,26,xxx
Samantha, 27,yyy

Output Json:
{"field1":"ArticleNumber","field2":"26","field3":"xxx\rArticleNumber,27,yyy"}

Thanks,
M.Roobini

**Comment by Keyang** [comment]
Hi,
The parser should be able to detect the line returns automatically. (\n ,\r
\n\r are supported)
I tested it with data provided it seems ok.
Below is my script to test it:
```
var csv='John,26,xxx\rSamantha,27,yyy';
var conv=new require("csvtojson").Converter({noheader:true});
conv.fromString(csv,console.log.bind(console));

```

and it gives:

```
[ { field1: 'John', field2: '22', field3: 'xxx' },
  { field1: 'Ketty', field2: '27', field3: 'yyy' } ]
```

Regards,
Keyang

**Comment by RoobiniM** [comment]
Could you please try saving the file in CSV (MAC) format and test it?

Thanks,
M.Roobini

**Comment by Keyang** [comment]
I tried. Same. Maybe format is different.
If you could upload the csv file you have problem with here, that would be
great.

Keyang

**Comment by RoobiniM** [comment]
Please find attached my file in txt format.
[MyCSV.txt](https://github.com/Keyang/node-csvtojson/files/68355/MyCSV.txt)

Thanks,
M.Roobini

**Comment by Keyang** [comment]
OIC.
The text file contains both "\r" and "\r\n" that the parser cannot detect
which one should be used for line break.
Simply you just explicitly indicate what eol should be used.
Here are examples:

```
var conv=new Converter({
    noheader:true,
    eol:"\r"  // this param says use \r as line break
})
```

~Keyang

**Comment by RoobiniM** [comment]
It is working fine now.
Thank you for your time and input :)

Thanks,
M.Roobini
