### ISSUE TITLE
Column type not working for array

### ISSUE THREAD

**Issue by tbenci** [Keyang/node-csvtojson#73]
Howdy,

I have a number of columns named Activity[0]..Activity[9]. These cells within the rows are either 0 or 1 but the conversion treats them as strings so a row looks like this in the JSON record

"Activity":["1","1","1","0","0","0","0","0","0","0"].

I tried the number#Activity[0] to no avail and other numbers are handled OK.

Any thoughts as to what I need to do to get the integers in the JSON.

Cheers
Tony Benci

**Comment by Keyang** [comment]
Hi,
Could you please upload the csv data and what you want it be converted to?

~Keyang

**Comment by tbenci** [comment]
Here you go,,,
[test.zip](https://github.com/Keyang/node-csvtojson/files/75768/test.zip)

**Comment by Keyang** [comment]
Thanks.
Patched in 0.5.1 please give a check.

~Keyang
