### ISSUE TITLE
Unmatched double quote bug

### ISSUE THREAD

**Issue by DirectX** [Keyang/node-csvtojson#75]
If CSV contains unmatched double quote processing stops on that line. Example:

```
foo,bar
a"bc,def
ghi,jkl
```

only first line will be processed

```
foo,bar
a"b"c,def
ghi,jkl
```

is ok.

I understand that this is not bug but feature. It's possible to get unclosed_quote error but how properly override such errors?

For now as a workaround I'm passing
    quote: "some unused sqmbol"
in initial params. Is it possible to permanently turn off using of quotes for some documents?

**Comment by Keyang** [comment]
Hi,
According to CSV basic rules (
https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules), double
quote is used for column containing commas e.g. a column value like "hello,
this is csvtojson"
A single double quote is represented as two double quotes together like ""
with csvtojson, you can use quote parameter to change the quote symbol to
another character.
Also, you can subscribe "error" event which will be fired if unclosed quote
has been detected. see
https://github.com/Keyang/node-csvtojson#error-handling

~Keyang

**Comment by DirectX** [comment]
Hi,

Thank you for your reply. Yes, I understand that it is right, but real world examples sometimes are very strange. To be more specific here is such one. This is US Federal Election Commission official data source (http://www.fec.gov/data/CandidateSummary.do?format=csv):

   1668:  "http://www.fec.gov/fecviewer/CandidateCommitteeDetail.do?candidateCommitteeId=P60016805&tabIndex=1","P60016805","MCMILLAN, JIMMY "RENT IS TOO DAMN HIGH","P","US","00","REP","OPEN","107 ST MARKS PL #1G","","MANHATTAN","NY","10009",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"",""

MCMILLAN, JIMMY "RENT IS TOO DAMN HIGH - funny candidate's name not valid of course. Very strange decision. Fortunately there is no known use case where actual commas in such fields are used.

There is also another option of zipped file with "|" delimiter instead of "," (ftp://ftp.fec.gov/FEC/2016/webl16.zip):

    4433: P60016805|MCMILLAN, JIMMY "RENT IS TOO DAMN HIGH|REP|2016|US|P|00|O|N|C00589457|107 ST MARKS PL #1G||MANHATTAN|NY|10009

In this case there is no ambiguity at all. It can be parsed with

    var converter = new Converter({ constructResult: false, headers: ["cand_id", "cand_name", "cand_pty_affiliation", "cand_election_yr", "cand_office_st", "cand_office", "cand_office_district", "cand_ici", "cand_status", "cand_pcc", "cand_st1", "cand_st2", "cand_city", "cand_st", "cand_zip"], quote: "Ψ", delimiter: "|", workerNum: 4 });

All I suppose is to think about more straightforward way to turn qioting off.

Thanks!

**Comment by Keyang** [comment]
This issue is fixed.
