### ISSUE TITLE
Parse Error with "#" at the end a header name

### ISSUE THREAD

**Issue by cbritton** [Keyang/node-csvtojson#76]
Using a file with this data in it (note the # at the end of the first header):

>album#, year, US_peak_chart_post
>The White Stripes, 1999, -
>De Stijl, 2000, -
>White Blood Cells, 2001, 61
>Elephant, 2003, 6
>Get Behind Me Satan, 2005, 3
>Icky Thump, 2007, 2
>Under Great White Northern Lights, 2010, 11
>Live in Mississippi, 2011, -
>Live at the Gold Dollar, 2012, -
>Nine Miles from the White City, 2013, -

Results in this error:

>    this.headStr = head.replace(this.regExp, '');
>                       ^

>RangeError: Maximum call stack size exceeded
>    at String.replace (native)

This only seems to happen when the # is the last character in any of the header elements. So, this will also fail: 

>album, year, US_peak_chart_post#

If # appears anywhere else in the file, the parse is successful.

**Comment by Keyang** [comment]
I will take a look soon.

~Keyang

**Comment by Keyang** [comment]
fixed in version 0.5.2

**Comment by cbritton** [comment]
Awesome! Thanks!
