### ISSUE TITLE
end_parsed not emitted

### ISSUE THREAD

**Issue by ruchevits** [Keyang/node-csvtojson#78]
My csv file is as follows:

    id, name
    1, Alice
    2, Bob

For some reason `end_parsed` event never gets fired.

    var converter = new Converter({
      constuctResult: true,
      delimiter: ',',
      trim: true
    });

    // Works fine
    converter.on("record_parsed", function (record) {
      console.log(record);
    });

    // Never fired
    converter.on("end_parsed",function(jsonObj){
      console.log('END PARSED')
    });
    
    readableStreamBuffer.pipe(converter);

What could be the reason?

Thanks,
Edw.

**Comment by ruchevits** [comment]
Actually, I apologize, the problem was with my stream.

Thanks for your work, guys!

**Comment by Keyang** [comment]
dont forget to listen to "error" event which will emit if any error happens
while parsing.

converter.on("error",handler)

~Keyang

**Comment by pdinesh80** [comment]
I'm facing similar issue, when I use "checkColumn: true", end or end_parsed is not emitted. I do see errors for the records (on error) not parsed correctly. But need "end" event to do the response.

Please advise if I'm missing anything.

**Comment by Keyang** [comment]
Could you let me know the version of you are using?

~Keyang

**Comment by pdinesh80** [comment]
I'm using the latest version 1.1.0

Thanks.

**Comment by Keyang** [comment]
Hi,
Thanks for the details.
I think node.js has implemented the stream this way:
if downstream emitted an error event it will unpipe automatically.
So if any error happens during parsing, the 'end' event will never been
emitted as 'error' event is suggesting the input stream has stopped.

according to https://nodejs.org/api/stream.html#stream_event_end, 'end'
will not be emited unless data is completely consumed.

from node.js source code (
https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L572-L583),
if 'error' being emitted, the stream will stop.

Thus, you can consider 'error' as 'end' in your scenario. You will need to
close input stream if error happens.

~Keyang

**Comment by Keyang** [comment]
I've added a 'done' event for this scenario:
https://github.com/Keyang/node-csvtojson#done

~Keyang

**Comment by pdinesh80** [comment]
@Keyang Great. Thanks a lot for your detailed explanation and the resolution.

QQ on 'done', so if my file has 15 records which contains 4 or 5 error records(which will emit "error" event when it encounter parse error), at the end of 15th record "done" will be emitted?

My requirement is to process the records in good order and reject the error records.

**Comment by Keyang** [comment]
Assume you have error on line 4 and 7, only line4 will be emitted then done will be emitted . It will stop and will not process other lines

**Comment by pdinesh80** [comment]
Thanks for your reply. is there a possibility to proceed till the end of
file even though some of the records in error.?

**Comment by Keyang** [comment]
Yeah set columnCheck false

Then you can use csv event to check each line has correct column number
