### ISSUE TITLE
Set header row to different row than 1st row.

### ISSUE THREAD

**Issue by lpgeiger** [Keyang/node-csvtojson#80]
There are many systems that export a csv with a few rows of metadata:
Consider a Google Play export:

```
ï»¿Per Transaction Report                    
Reporting Period:   2014-01-01 to 2014-01-31                
Native Retail Currency:     USD             
Country, Transaction, Date, Name of App
Usa, 24234jh24, 1/1/14, "App Name"
```

Is there any way to achieve this currently? 

I suggest a param like {skipToHeader: 4 } , to start from the 4th row.

**Comment by Keyang** [comment]
Hi,
It is a good proposal.
I will add it to feature road map..

~Keyang

**Comment by YouriT** [comment]
That would be great yes! And as a workaround for now, is there any way to achieve it.

**Comment by Keyang** [comment]
There are some work around.
My suggestion is to stream data through a transformer first which stripes
out the lines want to skip,.
For linux command line, use tail -n to skip the lines.

~Keyang

**Comment by YouriT** [comment]
Well I was using it in node so I had to use stream.Transform to achieve that.

Let me give you my solution as it might help @keyscores 
```js
var ret = r; // A stream basically
if (options.stripFirstNLines) {
    var parser = new Transform();
    parser._transform = function (data, encoding, done) {
        var arr = data.toString().split('\n');

        arr.splice(0, options.stripFirstNLines);
        this.push(new Buffer(arr.join('\n'), 'utf8'));
        done();
    };
    ret = r.pipe(parser);
}
return ret;
```

So basically I'm giving the pipe to the function (represented by `r`) and it will be repiped before being returned. I transform the CSV chunk to an array, then splicing the `firstNLines`, rebuffering it and pushing it to the stream again. As it the converter gets straightly clean data.

Hope it might help :)

**Comment by keyscores** [comment]
@Keyang for now I can do a workaround by skipping the rows that don't contain the objects in the pre-defined header. What's the best way to skip a row while in streaming mode?

**Comment by Keyang** [comment]
@keyscores, see answer from Youri. You need write your own Transform stream
instance to remove the headers.

~Keyang

**Comment by keyscores** [comment]
Exending on @YouriT  answer.  Here's a small tutorial for other people that have unecessary lines around the core data needed to parse. @Keyang please give me your comments to see if I understand this correctly.

Sometimes there are start and end rows that need to be ignored in the CSV. 
For example below I want to ignore lines 1-2 and also the last line. However it's not right to hard-code line 2 and line -1 . The extra lines may be variable.
```

Per Transaction Report,,,,,,,,,,,,,,,,,,,,,,,,,,,
"Reporting Period: ",2014-11-24 to 2014-11-30,,,,,,,,,,,,,,,,,,,,,,,,,,
header a, header b, header c
1, 2, 3
{many more lines of data...}
4, 5, 6
EST Totals:,,,,,,,,,,,,,,
```

So we can use a transform stream to check each chunk of data and split if it's necessary. Then we can do the piping to send it to the csvToJson stream writer.

```
var Transform = require('stream').Transform;
var parser = new Transform()

  removeExtraLines._transform = function(data, encoding, done) {

      //convert the data chunk buffer to utf8 string
      data = data.toString()
      
      // find the first instance of the header, which tells us when the data beings.
      var startPosition = data.toString().indexOf('Country,');
      // find the first instance of the footer summary text, which tells us when the data ends.
      var endPosition = data.toString().lastIndexOf('EST Totals:');

      //it's a small chunk with both start and end strings
      if( startPosition && endPosition){
       // .substr(start,end) will cut a string to the desired start and end index/positions.
        data = data.substr(startPosition, endPosition-startPosition)
        this.push(data);
        done();
        return;
      }

      // it's a large file and the first chunk only contains the startposition.
      if( startPosition && !endPosition){
        data = data.substr(startPosition)
        this.push(data);
        done();
        return;
      }

      //none of the strings are found. You are probably in the middle section of a large file. Do nothing and just pass the data.
      if( !startPosition && !endPosition){
        this.push(data);
        done();
        return;
      }

      //it's a large file and this is the the last chunk that contains the end position.
      if( !startPosition && endPosition){
        data = data.substr(-endPosition)
        this.push(data);
        done();
        return;
      }
  };

  //here is the final "plumbing" showing each pipe leading to the converter
  originalDataStream.pipe(removeExtraLines).pipe(csvToJsonConverter)
```

**Comment by MaffooBristol** [comment]
I just wanted to remove whitespace from the CSV, because (in my example) the file has a space before the header. But because `ignoreEmpty` only seems to account for rows and doesn't work with header, I had to use the examples above to polyfill my own stream transformation:

```javascript
var transform = function () {
  var parser = new require('stream').Transform(), trimmed = false;
  parser._transform = function (data, encoding, done) {
    if (trimmed) {
      this.push(data);
      return done();
    }
    trimmed = true;
    this.push(new Buffer(data.toString().trim(), 'utf8'));
    done();
  }
  return parser;
}
var file = fs.createReadStream('abc.csv');
var csvConverter = new csvtojson({constructResult: true, ignoreEmpty: true});
csvConverter.on('end_parsed', (data) => doSomething(null, data));
file.pipe(transform()).pipe(csvConverter);
```

Would much prefer it if `ignoreEmpty` applied to headers too, though. Is that an easy fix?

**Comment by shubsaini09** [comment]
@YouriT @Keyang May be dumb question but can you tell me where should i implement solution suggested by @YouriT in my code. Right now my code is

```
csvFilePath = Config.publicFolder+'/report.csv';
csv({noheader:false, headers: ['header1','header2','header3','header4']})
.fromFile(csvFilePath)
.on('end_parsed',(jsonObj)=>{
    reply(jsonObj);
})
.on('done',(error)=>{
    if(error){
        console.log('Error while reading file')
        console.log(error);
    }
    console.log('Report csv file read successfully')
})
```
Actually my first line of the csv file is heading and next is my headers so after using this code i am able to skip my heading but my first json object is my own headers which i dont want so how can i achieve that?
My current output
```
[
{'header1':"myheader1",
 'header1':"myheader2", 
'header2':"myheader3", 
'header4':"myheader4"
},
{...},
{...}
.....
]
```

**Comment by Keyang** [comment]
This feature can now be achieved through `fileRaw` and `fileLine` hooks
