### ISSUE TITLE
Support question - Extra CSV column

### ISSUE THREAD

**Issue by ORESoftware** [Keyang/node-csvtojson#81]
thanks for this lib, we have been using it in production for almost a year - can this lib check to see if a CSV file has an extra column? Looks like the `checkColumn: true` can check for missing headers, but what about an extra header/column in the .csv file? Please let me know, thanks!

(Currently, using this library, it is hard for me to tack on support for extra headers, seems like the best way and the only good way is to do it within this library.)

**Comment by Keyang** [comment]
Hi,
I am not sure why you need check if a CSV file has an extra column.
However try to set parameter ignoreEmpty=true. It will automatically skip empty columns.

~Keyang

**Comment by ORESoftware** [comment]
Well, I think it's my mistake - looks like checkColumn: true works for both extra columns and missing columns, does that make sense?

**Comment by Keyang** [comment]
Yeah. it will threw error if columns number not equal to that of header -- no matter more or less..

~Keyang
