### ISSUE TITLE
Charset conversion?

### ISSUE THREAD

**Issue by ciscoheat** [Keyang/node-csvtojson#82]
Any chance of adding charset conversion options? I have some Win-1252 files that must be converted to utf-8 before csvtojson works properly (it seems to assume utf-8). https://github.com/ashtuchkin/iconv-lite is a useful package for that.

**Comment by Keyang** [comment]
Hi,
Thanks for your suggestion.
charset conversion should not be part of csv converting.
It is suggested to use other libraries to convert data charset before being
sent to csvtojson.
With the lib you mentioned, you can either use full-text convert or stream
with csvtojson.

~Keyang

**Comment by ciscoheat** [comment]
Yes, thanks, I will use `iconv` on the command line to solve this.
