### ISSUE TITLE
first colunm escape quotes

### ISSUE THREAD

**Issue by chacliff** [Keyang/node-csvtojson#83]
Are you aware that your current version is adding escape quotes to its first colunm, in the header when it creates json? 

sample header:
"ProductID","NDC9","ProductNameLong","ProductNameTypeID","ProductNameShort",

sample data:
"137","00004-0239","product","3","soulja",
"142","00173-0682","Ventolin HFA 90mcg/actuation Inhalation Aerosol","3","Ventolin HFA 90mcg/act Inhaler",

sample output: 
{"\"ProductID\"":"137","NDC9":"00004-0239", "ProductNameLong": "product", "ProductNameTypeID": 3, "ProductNameShort":"soulja" }

is there a reason this is happening? i don't think it makes much sense to add \" on the first property. 
but i am thankful for the ignore blanks that you have :+1:

**Comment by Keyang** [comment]
Hi,
I cannot reproduce the issue you have there.
With the latest version 0.5.2, the csv data

"ProductID","NDC9","ProductNameLong","ProductNameTypeID","ProductNameShort",
"137","00004-0239","product","3","soulja",
"142","00173-0682","Ventolin HFA 90mcg/actuation Inhalation
Aerosol","3","Ventolin HFA 90mcg/act Inhaler",

is converted to :

[
{"ProductID":137,"NDC9":"00004-0239","ProductNameLong":"product","ProductNameTypeID":3,"ProductNameShort":"soulja","field6":""},
{"ProductID":142,"NDC9":"00173-0682","ProductNameLong":"Ventolin HFA
90mcg/actuation Inhalation
Aerosol","ProductNameTypeID":3,"ProductNameShort":"Ventolin HFA 90mcg/act
Inhaler","field6":""}
]

You can give a try with your data here: http://keyangxiang.com/csvtojson/

Regards,
Keyang

**Comment by chacliff** [comment]
it looks like it worked fine from the website, i'm using it to convert large files with a node script. some large and some small. I'm running it locally on a windows 7 64 bit system. 

I'm guessing its running on a *nix server for the site. 
Here is my code, relatively straightforward. 

var Converter=require("csvtojson").Converter;
var Promise = require("bluebird"); 
var fs = Promise.promisifyAll(require("fs"));

var csvConverter=new Converter({constructResult:false, 
ignoreEmpty: true
});
fs.mkdirSync("data"); 
var readStream=require("fs").createReadStream("Specific_Product.csv");
 
var writeStream=require("fs").createWriteStream("data/Specific_Product.json");
readStream.pipe(csvConverter).pipe(writeStream);

**Comment by Keyang** [comment]
Hi,
The script looks fine for me.Just one thing: use toArrayString:true
parameter to stream down a real json array string rather than json strings.
If you could upload the csv file that you have problem with, that would be
very helpful for me to diagnose the issue.

Regards,
Keyang

**Comment by chacliff** [comment]
i can't upload the files due to copyright issues, but all the files have the same problem, its not just one file. The most i can do is give you the headers. 

I can't use it with toArrayString because i am uploading the data to mongodb with a mongoimport call and need the data to just be a list of objects in this case. 

This is one of the headers. I am thinking this is a windows specific issue since my local dev enviroment is windows. unless you might think otherwise?
"SpecificProductID","SpecificDrugProductID","SpecificNondrugProductID","Name","Synonym", ""

**Comment by chacliff** [comment]
ok so after pulling the first row out of the file and passing the header into your "headers" parameter it doesn't seem to be having an issue any longer. 

I tried to overwrite the header in the file and save it, still got the same result. 

Copy pasting the text to a new file seemed resulted in the expected values. 

I also just made a copy of the original file and did the conversion on the new copy and got the expected result. 

When i retrieved the original file onto my computer from SFTP it must have done something that is causing this bug. Although its only a theory.

**Comment by Keyang** [comment]
Hmm.
sounds like an encoding issue.
You better use other stream based libraries like iconv to convert the
source file to "utf8" before streaming it to csvtojson.
the website sent you does not have a server but browser version of
csvtojson running in your browser so it should have the same context.

~Keyang

**Comment by chacliff** [comment]
yeah that would make sense, thanks

**Comment by chacliff** [comment]
fyi, i found out that it was a non-printable control character at the beginning of the document. 
I figured out how to remove it, now i'm just determining how i best want to proceed in order to continue using your module.
