### ISSUE TITLE
Add ndjson support

### ISSUE THREAD

**Issue by balihoo-dengstrom** [Keyang/node-csvtojson#87]
Would it be possible to add an optional parameter that outputs results in [ndjson format](http://ndjson.org/)?

Example CSV:
```
id,name
a,foo
b,bar
```

Current json output:
```json
[
{"id":"a","name":"foo"},
{"id":"b","name":"bar"}
]
```

Proposed ndjson output:
```json
{"id":"a","name":"foo"}
{"id":"b","name":"bar"}
```

**Comment by Keyang** [comment]
Are you using CLI or Lib?
If lib, just set toArrayString to false

~Keyang

**Comment by balihoo-dengstrom** [comment]
I was using the CLI. I'll try the Lib instead. Thanks!

**Comment by Keyang** [comment]
Thanks. I will add this as a feature for CLI soon.

~Keyang
