### ISSUE TITLE
Error: write after end when csvConverter.fromString is called two times

### ISSUE THREAD

**Issue by flexbrane** [Keyang/node-csvtojson#89]
My program need to parse two csv files that are stored in a json object : 

```js
csv_files = [
               {
                  "name" : "<name>",
                  "file" : "./file.csv"
               },
               [...]
           ]
```

I use `async` to execute some part of my code synchronously. And in my main program I read all file from `csv_files` in order to parse all csv.

If I call one time `csvConverter.fromString` it's works perfectly. But when I want to do a loop (something like that) I have `Error: write after end`.

With this code :

```js
[...]
        allCsv2bdd_url(csv_files[i], function(err){
            if(csv_files.length > i){
                i++;
                allCsv2bdd_url(csv_files[i], function(err){});
            }else {
                done();
            }
        });
```

I have the error message.

In `allCsv2bdd_url` I execute two functions in synchronous mode, including the `csvtojson` function.

```js
    var csvLines = '';

    //- Read Lines
    try{
        fs.readFileSync(csv_file).toString().split('\n').forEach(function (line) {
            csvLines += line;
            console.log(' [url.csv] '+line);
        });
        //- Transform lines to json
        csvConverter.fromString(csvLines, function(err, jsonObj){
            if (err){
                console.log('\n [url.csv] An error as occured when trying to convert csv to JSON :\n\t'+err);
                callback( );
            } else {
                callback( jsonObj );
            }
        });
    }catch(e){
        console.log('\n [url.csv] /!\\ Cannot access to file '+csv_file+' with the following error :\n\t'+e);
        callback( );
    }
```

Is someone can explain why I have this problem ? 

Thanks :)

**Comment by flexbrane** [comment]
First I was thinking that I was because of `async` but now I am not sure, that is why I ask you here some help !
(Previous issue on `async` : https://github.com/caolan/async/issues/1116)

**Comment by flexbrane** [comment]
I tried to slightly modify my code :

```js
    try{
        //- Transform file lines to json
        csvConverter.fromFile(csv_file,function(err,jsonObj){
            if (err){
                console.log('\n [url.csv] An error as occured when trying to convert csv to JSON :\n\t'+err);
                callback( );
            } else {
                callback( jsonObj );
            }
        });
    }catch(e){
        console.log('\n [url.csv] /!\\ Cannot access to file '+csv_file+' with the following error :\n\t'+e);
        callback( );
    }
```

Same error

**Comment by Keyang** [comment]
Hi,
You have to create new Converter instance for different files.
Converter is based on stream. Once a file processing finished, the stream
is closed. To process another file, create new converter.

~Keyang

**Comment by flexbrane** [comment]
Thank you so much :)

**Comment by dolanmiu** [comment]
I had the same issue and took me 3 hours to figure out the problem

I feel this needs to be more clear, a more descriptive error than:

`"write after end"`

**Comment by Keyang** [comment]
Thanks.
I will make this better in next version.

~Keyang
