### ISSUE TITLE
Inconsistent removal of quotation marks

### ISSUE THREAD

**Issue by dchw** [Keyang/node-csvtojson#92]
Given data like this:
`"Column 1","Column 2","Column 3","Email"
Column1Row1,Column2Row1,Column3Row1,Row1@example.com`

I get this output:
`[ { 'Column 1': 'Column1Row1',
    'Column 2': 'Column2Row1',
    'Column 3': 'Column3Row1',
    Email: 'Row1@example.com' } ]`

but, if I have data like this (note the extra spaces):
`"Column 1"  ,  "Column 2",  "Column 3"  ,"Email"
Column1Row1,Column2Row1,Column3Row1,Row1@example.com`

I get this output (note the quoted header row names):
`[ { '"Column 1"': 'Column1Row1',
    '"Column 2"': 'Column2Row1',
    '"Column 3"': 'Column3Row1',
    Email: 'Row1@example.com' } ]`

With `trim` defaulting to true, I would expect the removal of the extraneous whitespace to result in the same output as the first example. Is this not correct?

**Comment by Keyang** [comment]
Thanks for pointing it out. I will get this fixed soon.

~Keyang

**Comment by Keyang** [comment]
Fixed 0.5.6
