### ISSUE TITLE
Reference error in Converter.js

### ISSUE THREAD

**Issue by tjabell** [Keyang/node-csvtojson#93]
I think this line:

`   data = this._csvLineBuffer;`

should be:

`   var data = this._csvLineBuffer;`

in libs/core/Converter.js line 262 [https://github.com/Keyang/node-csvtojson/blob/master/libs/core/Converter.js#L262](https://github.com/Keyang/node-csvtojson/blob/master/libs/core/Converter.js#L262)

**Comment by Keyang** [comment]
thanks for pointing out.

~Keyang
