### ISSUE TITLE
Remove line-feed, carriage-return and extra spaces from header names

### ISSUE THREAD

**Issue by BlazeSahlzen** [Keyang/node-csvtojson#94]
While doing a project in which I had to convert a CSV file to JSON before further processing, I found that the CSV headers in many cases contained _line-feeds_ and _carriage-returns_ as well as _extra-spaces_ in between characters.

By default, they are kept untouched and appear as `\r`, `\n` and `     ` (_extra spaces_) in the JSON object's keys. It would be a nice addition to this package if there was an option to remove them by default.

One could simply ignore this, however, in my case this posed a problem as the files received from the client would frequently have altered header names simply due to these characters (which non-code savvy people would find hard to detect and could easily break a system).

**Comment by Keyang** [comment]
Hi,
You have several ways:
1. tell parser to replace csv headers with your one e.g. csvtojson ./mycsv
 --headers='["hello","csv"]'
2. set "trim" to true to trim any spaces in a column (make sure you have
latest csvtojson parser)

~Keyang

**Comment by BlazeSahlzen** [comment]
Hi,

It seems I had somehow missed the `headers` option. I couldn't make use of it initially as the CSV headers changed frequently, so instead I had resorted to processing the keys in the output object (from `"record_parsed"` event of `csvtojson`) and created a new object before further processing.

In future, I'll be sure to use the `headers` option once the CSV headers are finalised.

Regards,
Blaze
