### ISSUE TITLE
Double quote returned when csv contains an empty quoted string

### ISSUE THREAD

**Issue by jondayft** [Keyang/node-csvtojson#95]
If the following csv data is converted:

```
"green", 40, ""
```

The converter will return 

```
{
  a: 'green',
  b: 50,
  c: ' " '
}
```

Where the property c is set to one double quote rather than an empty string

Please see the following commit for failing test case https://github.com/jondayft/node-csvtojson/commit/96c75a18d76a48c4548f5024aa6ced592163da9a

This doesn't seem like desired behaviour and I couldn't see any options that could be passed through to as configuration to solve?

**Comment by Keyang** [comment]
Thanks for pointing out. This was bug introduced in v 0.5.7

~Keyang

**Comment by jondayft** [comment]
Thanks for the quick fix
